#!/bin/zsh

chdir ${1:-.}

dirs=(configs htdocs include plugins scripts templates)
opts=(-type f -not -path '*CVS*' -not -name '.cvsignore')

diff -u <(cat install.d/**/files|sort) <(find $dirs $opts|sort) \
    | grep '^[-+][a-z]' | sed -e 's,^+,Orphaned: ,;s,^-,Missing : ,'
