ALTER TABLE adresses           MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE aliases            MODIFY COLUMN id             INT NOT NULL DEFAULT 0;
ALTER TABLE applis_ins         MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE auth_user_md5      MODIFY COLUMN user_id        INT NOT NULL AUTO_INCREMENT;
ALTER TABLE auth_user_quick    MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE axletter_ins       MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE axletter_rights    MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE binets_ins         MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE competences_ins    MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE contacts           MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE email_send_save    MODIFY COLUMN uid            INT NOT NULL;
ALTER TABLE emails_watch       MODIFY COLUMN uid            INT DEFAULT NULL;
ALTER TABLE entreprises        MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE evenements         MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE evenements_vus     MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE gapps_accounts     MODIFY COLUMN l_userid       INT DEFAULT NULL;
ALTER TABLE gapps_queue        MODIFY COLUMN q_owner_id     INT DEFAULT NULL;
ALTER TABLE gapps_queue        MODIFY COLUMN q_recipient_id INT DEFAULT NULL;
ALTER TABLE groupesx_ins       MODIFY COLUMN guid           INT NOT NULL DEFAULT 0;
ALTER TABLE homonymes          MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE ip_watch           MODIFY COLUMN uid            INT DEFAULT NULL;
ALTER TABLE langues_ins        MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE mentor             MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE mentor_pays        MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE mentor_secteurs    MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE ml_moderate        MODIFY COLUMN mid            INT NOT NULL;
ALTER TABLE ml_moderate        MODIFY COLUMN uid            INT NOT NULL;
ALTER TABLE newsletter_ins     MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE perte_pass         MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE photo              MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE profile_medals_sub MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE register_subs      MODIFY COLUMN uid            INT NOT NULL;
ALTER TABLE survey_surveys     MODIFY COLUMN author_id      INT NOT NULL;
ALTER TABLE survey_votes       MODIFY COLUMN user_id        INT NOT NULL;
ALTER TABLE tels               MODIFY COLUMN uid            INT NOT NULL DEFAULT 0;
ALTER TABLE user_changes       MODIFY COLUMN user_id        INT NOT NULL DEFAULT 0;
ALTER TABLE watch_profile      MODIFY COLUMN uid            INT NOT NULL;

# vim:set syntax=mysql:
