ALTER TABLE adresses
CHANGE ville city VARCHAR(80) DEFAULT '' NOT NULL,
CHANGE cp postcode VARCHAR(20) DEFAULT '' NOT NULL,
CHANGE pays country VARCHAR(2) DEFAULT '00' NOT NULL;
ALTER TABLE entreprises
CHANGE ville city VARCHAR(80) DEFAULT '' NOT NULL,
CHANGE cp postcode VARCHAR(20) DEFAULT '' NOT NULL,
CHANGE pays country VARCHAR(2) DEFAULT '00' NOT NULL;

