#!/usr/bin/perl
use utf8;
$path = $0;
$path =~ s/modules\/fusionax\/formation\.pl//;
$path .= "spool/fusionax/";
$in = $path . "Formations.txt";
$out = $path . "Formations_out.txt";
open(FILE, "<:encoding(UTF-8)", $in) || die ("Formations.txt failed to open.");
open(OUT, ">:encoding(UTF-8)", $out) || die ("Formations_out.txt failed to open.");

while (<FILE>)
{
  # Dates removal.
  s/\r$//;
  s/(\t)*[0-9]+\t[0-9]+\t([0-9]{2}\/){2}[0-9]+$//;
  # Trailing tab, spaces and dot removal.
  s/(\t| )*$//;
  s/( \t|\t )/\t/g;
  s/(\.|\(|\))//g;
  s/ +/ /g;

  # Removes empty educations and jobs (they have nothing to do there).
  s/^FO\t\w{8}$//;
  s/^FO\t\w{8}\tProfdes Universités$//;
  s/^FO\t\w{8}\tPréshonColonie Frdu Caire$//;
  s/^FO\t\w{8}\tInspgénhonCEA$//;
  s/^FO\t\w{8}\tProf Emérite Gén Méca$//;
  s/^FO\t\w{8}\tAncDG Dassault Aviation$//;
  s/^FO\t\w{8}\tPilote militaire Hélicoptère$//;
  s/^FO\t\w{8}\tProfHonSupAéro$//;
  s/^FO\t\w{8}\tPilote de chasse$//;
  s/^FO\t\w{8}\tProf ENSMP$//;
  s/^FO\t\w{8}\tProf hon Univ Bordeaux I$//;
  s/^FO\t\w{8}\tProf$//;
  s/^FO\t\w{8}\tIng Navigant d'Essais Hélicoptère$//;
  s/^FO\t\w{8}\tMandataire agrée OEB$//;
  s/^FO\t\w{8}\tIngSt$//;
  s/^FO\t\w{8}\tIngretrAérospatiale$//;
  s/^FO\t\w{8}\tIngénieur$//;
  s/^FO\t\w{8}\tIng EURATOM$//;
  s/^FO\t\w{8}\tInspGénCRdes Affd'OM$//;
  s/^FO\t\w{8}\tAvocat au Barreau de Paris$//;
  s/^FO\t\w{8}\tCambridge Profic$//;
  s/^FO\t\w{8}\tPilotage militaire$//;
  s/^FO\t\w{8}\tDirectHonBNP$//;
  s/^FO\t\w{8}\tInspecteur des Finances$//;
  s/^FO\t\w{8}\tMITI Japon$//;
  s/^FO\t\w{8}\tEuropean Patent Attorney$//;
  s/^FO\t\w{8}\tAdmciv$//;
  s/^FO\t\w{8}\tDirecthon SNCF$//;
  s/^FO\t\w{8}\tDDI Informatique$//;
  s/^FO\t\w{8}\tDDI$//;
  s/^FO\t\w{8}\tSFAF$//;
  s/^FO\t\w{8}\tGestalt praticien$//;
  s/^FO\t\w{8}\tAdmciv HC$//;
  s/^FO\t\w{8}\tPsychologue Clinicien$//;
  s/^FO\t\w{8}\tAnc Avocat au Bareau de Toulon$//;
  s/^FO\t\w{8}\tAnalyste SFAF$//;
  s/^FO\t\w{8}\tEcole de Chasse$//;
  s/^FO\t\w{8}\tPost Doc$//;
  s/^FO\t\w{8}\tSFAF CIIA$//;
  s/^FO\t\w{8}\tINSEE$//;
  s/^FO\t\w{8}\tEconomiste Statisticien$//;
  s/^\n//;
  # Places education in third place as if it is not reconized, it will only be stored as a description.
  s/^(FO\t\w{8}\t)/\1\t\t/;

  # Fixes what can be fixed.
  # École d'Ingénieurs
  s/\t\t\tENS Armement$/\tArmement\tCorps\t/;
  s/\t\t\tENS Géographiques$/\tGéographes\tCorps\t/;
  s/\t\t\tEcole Nat des Sc Géographiques$/\tGéographes\tCorps\t/;
  s/\t\t\tIngENSIMAG$/\tENSIMAG\tIng.\t/;
  s/\t\t\tIngESTP$/\tESTP\tIng.\t/;
  s/\t\t\tIng IEG$/\tENSIEG\tIng.\t/;
  s/\t\t\tMIB Ponts$/\tPonts\tMIB\t/;
  s/\t\t\tMPA Ponts$/\tPonts\tMBA\t/;
  s/\t\t\tMBA Ponts et Chaussées$/\tPonts\tMBA\t/;
  s/\t\t\tMBA Ponts$/\tPonts\tMBA\t/;
  s/\t\t\tMaster PC$/\tPonts\tM\t/;
  s/\t\t\tENPC$/\tPonts\tIng.\t/;
  s/\t\t\tMIB ENPC$/\tPonts\tMIB\t/;
  s/\t\t\tMBA ENPC$/\tPonts\tMBA\t/;
  s/\t\t\tMaster ENPC Action publique$/\tPonts\tM\tAction publique/;
  s/\t\t\tIngcivPC$/\tPonts\tIng.\t/;
  s/\t\t\tIngSupelec$/\tSupélec\tIng.\t/;
  s/\t\t\tIngESE$/\tSupélec\tIng.\t/;
  s/\t\t\tESE$/\tSupélec\tIng.\t/;
  s/\t\t\tIng Supoptique$/\tSupOptique\tIng.\t/;
  s/\t\t\tSupoptique$/\tSupOptique\tIng.\t/;
  s/\t\t\tIngINSTN$/\tINSTN\tIng.\t/;
  s/\t\t\tIngINSTN Génie Atomique$/\tINSTN\tIng.\tGénie Atomique/;
  s/\t\t\tIngArts et Métiers$/\tENSAM\tIng.\t/;
  s/\t\t\tIngIFFI$/\tENSAM\tIng.\t/;
  s/\t\t\tENSAM$/\tENSAM\tIng.\t/;
  s/\t\t\tENSAR$/\tENSAR\tIng.\t/;
  s/\t\t\tIng INA PG$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tIngénieur INAPG$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tINAPG$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tIngAgronome$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tIng AgroParisTech$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tAgro Paris Tech$/\tAgroParisTech\tIng.\t/;
  s/\t\t\tDEA EERN$/\tAgroParisTech\tDEA\tEERN/;
  s/\t\t\tDEA EERN Economie de l'Environnement$/\tAgroParisTech\tDEA\tEERN Economie de l'Environnement/;
  s/\t\t\tMaster AgroParisTech$/\tAgroParisTech\tM\t/;
  s/\t\t\tIngENST Bretagne$/\tTélécom Bretagne\tIng.\t/;
  s/\t\t\tIngENST$/\tTélécom\tIng.\t/;
  s/\t\t\tENSTP$/\tTélécom\tIng.\t/;
  s/\t\t\tIngcivTéléc$/\tTélécom\tIng.\t/;
  s/\t\t\tMastère SSIR de l'ENST$/\tTélécom\tM\tSSIR/;
  s/\t\t\tMSc Télécom Jussieu$/\tTélécom\tMSc\t/;
  s/\t\t\tMaster CAR ENST$/\tTélécom\tM\tCAR/;
  s/\t\t\tDoctENST$/\tTélécom\tPhD\t/;
  s/\t\t\tPhDTéléc$/\tTélécom\tPhD\t/;
  s/\t\t\tPhD Télécom$/\tTélécom\tPhD\t/;
  s/\t\t\tIngENSPM$/\tENSPM\tIng.\t/;
  s/\t\t\tIngIFP$/\tENSPM\tIng.\t/;
  s/\t\t\tIngENSPM Options Moteurs$/\tENSPM\tIng.\tOptions Moteurs/;
  s/\t\t\tIngENSPM Raffinage$/\tENSPM\tIng.\tRaffinage/;
  s/\t\t\tENSPM$/\tENSPM\tIng.\t/;
  s/\t\t\tIngENSIC$/\tENSIC\tIng.\t/;
  s/\t\t\tIng ENSIC$/\tENSIC\tIng.\t/;
  s/\t\t\tENSIC$/\tENSIC\tIng.\t/;
  s/\t\t\tENSIC Nancy$/\tENSIC\tIng.\t/;
  s/\t\t\tIngCivENSIC$/\tENSIC\tIng.\t/;
  s/\t\t\tENSP$/\tENSP\tDipl.\t/;
  s/\t\t\tENSP Versailles$/\tENSP\tDipl.\t/;
  s/\t\t\tENSCP$/\tChimie Paris\tIng.\t/;
  s/\t\t\tIng Chimie Paris$/\tChimie Paris\tIng.\t/;
  s/\t\t\tIng : Chimie Paris$/\tChimie Paris\tIng.\t/;
  s/\t\t\tIngcivMétéo$/\tMétéo\tIng.\t/;
  s/\t\t\tIngcivM$/\tMines\tIng.\t/;
  s/\t\t\tIngcivMines Paris$/\tMines\tIng.\t/;
  s/\t\t\tMSc ISIGE$/\tMines\tMSc\tISIGE/;
  s/\t\t\tMS Mines$/\tMines\tMSc\t/;
  s/\t\t\tMSc Mines$/\tMines\tMSc\t/;
  s/\t\t\tMSc : Mines$/\tMines\tMSc\t/;
  s/\t\t\tDoctENSMP$/\tMines\tPhD\t/;
  s/\t\t\tPhD Mines$/\tMines\tPhD\t/;
  s/\t\t\tPhD Mines Paris$/\tMines\tPhD\t/;
  s/\t\t\tIngcivPC Management Industriel$/\tPonts\tIng.\tManagement Industriel/;
  s/\t\t\tMBA Ponts Paris Tech$/\tPonts\tMBA\t/;
  s/\t\t\tDoctENPC$/\tPonts\tPhD\t/;
  s/\t\t\tPhD Ponts$/\tPonts\tPhD\t/;
  s/\t\t\tIngcivAéro$/\tSUPAERO\tIng.\t/;
  s/\t\t\tSupAéro$/\tSUPAERO\tIng.\t/;
  s/\t\t\tIng SupAéro$/\tSUPAERO\tIng.\t/;
  s/\t\t\tIngénieur Supaéro$/\tSUPAERO\tIng.\t/;
  s/\t\t\tDoctIngSup'Aéro$/\tSUPAERO\tPhD\t/;
  s/\t\t\tDoctorat Supaéro$/\tSUPAERO\tPhD\t/;
  s/\t\t\tSupAéro : PhD$/\tSUPAERO\tPhD\t/;
  s/\t\t\tPhD Supaéro$/\tSUPAERO\tPhD\t/;
  s/\t\t\tIngcivGM$/\tÉcole Nationale Supérieure du Génie Maritime\tIng.\t/;
  s/\t\t\tENSGM$/\tÉcole Nationale Supérieure du Génie Maritime\tIng.\t/;
  s/\t\t\tIngcivENSTA$/\tENSTA\tIng.\t/;
  s/\t\t\tIng ENSTA$/\tENSTA\tIng.\t/;
  s/\t\t\tENSTA$/\tENSTA\tIng.\t/;
  s/\t\t\tENSTA Environnement marin$/\tENSTA\tIng.\tEnvironnement marint/;
  s/\t\t\tMBA ENSTA$/\tENSTA\tMBA\t/;
  s/\t\t\tThèse Chimie Organique ENSTA$/\tENSTA\tPhD\tChimie Organique/;
  s/\t\t\tIngcivGREF$/\tENGREF\tIng.\t/;
  s/\t\t\tENGREF$/\tENGREF\tIng.\t/;
  s/\t\t\tEcole Nat Eaux et Forêt Nancy$/\tENGREF\tIng.\t/;
  s/\t\t\tDoct ENGREF$/\tENGREF\tPhD\t/;
  s/\t\t\tPhD ENGREF$/\tENGREF\tPhD\t/;
  s/\t\t\tDocten Sc de l'environnement ENGREF$/\tENGREF\tPhD\tEnvironnement/;
  s/\t\t\tPhD Engref$/\tENGREF\tPhD\t/;
  s/\t\t\tIng ENSHG$/\tENSHMG\tIng.\t/;
  s/\t\t\tIng ISCM$/\tISMCM Saint-Ouen\tIng.\t/;
  s/\t\t\tISMCM Saint-Ouen$/\tISMCM Saint-Ouen\tIng.\t/;
  s/\t\t\tIng ENSIEG$/\tENSIEG\tIng.\t/;
  s/\t\t\tCESS de l'ENSAÉ$/\tENSAE\tIng.\t/;
  s/\t\t\tENSAE$/\tENSAE\tIng.\t/;
  s/\t\t\tIng ENSAE$/\tENSAE\tIng.\t/;
  s/\t\t\tENSAE Malakoff$/\tENSAE\tIng.\t/;
  s/\t\t\tENSAE Statisticien économiste$/\tENSAE\tIng.\t/;
  s/\t\t\tENSAE Ingénieur$/\tENSAE\tIng.\t/;
  s/\t\t\tENSAE ingénieur$/\tENSAE\tIng.\t/;
  s/\t\t\tIngénieur ENSAE$/\tENSAE\tIng.\t/;
  s/\t\t\tDoctENSAE$/\tENSAE\tPhD\t/;
  s/\t\t\tIng de l'Institut Polytechnique de Grenoble$/\tGrenoble INP\tIng.\t/;
  s/\t\t\tDEA INPG$/\tGrenoble INP\tDEA\t/;
  s/\t\t\tDoctINPG$/\tGrenoble INP\tPhD\t/;
  s/\t\t\tPhD INPG$/\tGrenoble INP\tPhD\t/;
  s/\t\t\tPhD : INPG$/\tGrenoble INP\tPhD\t/;
  s/\t\t\tDEA IHM INPT$/\tINP Toulouse\tDEA\tIHM/;
  s/\t\t\tDocteur INP Toulouse maths info$/\tINP Toulouse\tPhD\tMathématiques Informatique/;
  s/\t\t\tDEA INPL$/\tINPL\tDEA\t/;
  s/\t\t\tIng INPL Institut National Polytechnique de Lorraine$/\tINPL\tIng.\t/;
  s/\t\t\tESMIM de Nancy$/\tINPL\tIng.\tESMIM/;
  s/\t\t\tPhD INPL$/\tINPL\tPhD\t/;
  s/\t\t\tDoctENSME$/\tENSMSE\tPhD\t/;
  s/\t\t\tESPCI$/\tESPCI\tIng.\t/;
  s/\t\t\tESPCI Ecole Sup Phys et de Chimie Industrielles$/\tESPCI\t\t/;
  s/\t\t\tIngESPCI$/\tESPCI\tIng.\t/;
  s/\t\t\tIng ESPCI$/\tESPCI\tIng.\t/;
  s/\t\t\tIngENSEEIHT$/\tENSEEIHT\tIng.\t/;
  s/\t\t\tIngENSEEIHT Informatique$/\tENSEEIHT\tIng.\tInformatique/;
  s/\t\t\tIngENSEEIHT Toulouse$/\tENSEEIHT\tIng.\t/;
  s/\t\t\tIngECP$/\tCentrale Paris\tIng.\t/;
  s/\t\t\tIngEcole Centrale$/\tCentrale Paris\tIng.\t/;
  s/\t\t\tDoctECP$/\tCentrale Paris\tPhD\t/;
  s/\t\t\tDEA TACS ENS Cachan$/\tENS Cachan\tDEA\tTACS/;
  s/\t\t\tDEA ENS Cachan$/\tENS Cachan\tDEA\t/;
  s/\t\t\tENS Cachan$/\tENS Cachan\tM\t/;
  s/\t\t\tMSc ENS Cachan$/\tENS Cachan\tMSc\t/;
  s/\t\t\tDoct\ ENS CACHAN Math Appliquée$/\tENS Cachan\tPhD\tMathématiques Appliquées/;
  s/\t\t\tPhD ENS Cachan$/\tENS Cachan\tPhD\t/;
  s/\t\t\tPhD Cachan$/\tENS Cachan\tPhD\t/;
  s/\t\t\tDEA ENS Lyon$/\tENS Lyon\tDEA\t/;
  s/\t\t\tDEA PhysThéor ENS Lyon$/\tENS Lyon\tDEA\tPhysique théorique/;
  s/\t\t\tENS Lyon$/\tENS Lyon\tM\t/;
  s/\t\t\tDoct ENS Lyon$/\tENS Lyon\tPhD\t/;
  s/\t\t\tDoctorat ENS Lyon$/\tENS Lyon\tPhD\t/;
  s/\t\t\tDEA : ENS$/\tENS Ulm\tDEA\t/;
  s/\t\t\tDEA ENS$/\tENS Ulm\tDEA\t/;
  s/\t\t\tENS Ulm DEA$/\tENS Ulm\tDEA\t/;
  s/\t\t\tDEA ENS Ulm$/\tENS Ulm\tDEA\t/;
  s/\t\t\tDEA : ENS Ulm$/\tENS Ulm\tDEA\t/;
  s/\t\t\tDEA ENs Ulm$/\tENS Ulm\tDEA\t/;
  s/\t\t\tENS Ulm : DEA$/\tENS Ulm\tDEA\t/;
  s/\t\t\tENS Ulm :DEA$/\tENS Ulm\tDEA\t/;
  s/\t\t\tENS$/\tENS Ulm\tM\t/;
  s/\t\t\tENS Ulm$/\tENS Ulm\tM\t/;
  s/\t\t\tMSc ENS Ulm$/\tENS Ulm\tMSc\t/;
  s/\t\t\tMSc ENS$/\tENS Ulm\tMSc\t/;
  s/\t\t\tMS ENS Ulm$/\tENS Ulm\tMSc\t/;
  s/\t\t\tPhD ENS Ulm$/\tENS Ulm\tPhD\t/;
  s/\t\t\tPhD ENS$/\tENS Ulm\tPhD\t/;
  s/\t\t\tPhD ENS$/\tENS Ulm\tPhD\t/;
  s/\t\t\tENS Ulm : PhD$/\tENS Ulm\tPhD\t/;
  s/\t\t\tDEA X$/\tX\tDEA\t/;
  s/\t\t\tDEA Ec polytechnique Chimie Orga$/\tX\tDEA\tChimie organique/;
  s/\t\t\tMaster de l'Ec polytechnique (.*)$/\tX\tM\t\1/;
  s/\t\t\tMaster de l'Ec Polytechnique (.*)$/\tX\tM\t\1/;
  s/\t\t\tEtudiant en Master de l'Ec polytechnique (.)*$/\tX\tM\t\1/;
  s/\t\t\tEtudiante en Master de l'Ec polytechnique (.)*$/\tX\tM\t\1/;
  s/\t\t\tMaster de l'X (.)*$/\tX\tM\t\1/;
  s/\t\t\tMaster de l'X$/\tX\tM\t/;
  s/\t\t\tMaster X Projet-Innovation-Conception$/\tX\tM\tProjet-Innovation-Conception/;
  s/\t\t\tMaster PIC$/\tX\tM\tPIC/;
  s/\t\t\tDoct de l'Ec polytechnique (.*)$/\tX\tPhD\t\1/;
  s/\t\t\tDoct de l'Ec Polytechnique (.*)$/\tX\tPhD\t\1/;
  s/\t\t\tDoct de l'Ec polytechnique$/\tX\tPhD\t/;
  s/\t\t\tDoct de l'Ec Polytechnique$/\tX\tPhD\t/;
  s/\t\t\tDoct de l'Ec polytechniqueMath$/\tX\tPhD\tMathématiques/;
  s/\t\t\tDoct de l'Ec polytechniqueMécanique$/\tX\tPhD\tMécanique/;
  s/\t\t\tPhD X$/\tX\tPhD\t/;
  s/\t\t\tENAC$/\tENAC\tDipl.\t/;

  # Other french educations.
  s/\t\t\tCollège InterArmées de Défense$/\tCollège Interarmées de Défense\tDipl.\t/;
  s/\t\t\tCollège Interarmées de Défense$/\tCollège Interarmées de Défense\tDipl.\t/;
  s/\t\t\tCollège des Ing$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Collège des Ing$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Collèges des Ing$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Collège des Ingénieurs$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Collège Ing$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Collède des Ing$/\tCDI\tMBA\t/;
  s/\t\t\tCDI$/\tCDI\tMBA\t/;
  s/\t\t\tMBA CDI$/\tCDI\tMBA\t/;
  s/\t\t\tMBA Institut d'Administration des Entreprises$/\tIAE de Paris\tMBA\t/;
  s/\t\t\tMBA IAE$/\tIAE de Paris\tMBA\t/;
  s/\t\t\tMS IAE$/\tIAE de Paris\tMSc\t/;
  s/\t\t\tDESS CAAE IAE$/\tIAE de Paris\tDESS\t/;
  s/\t\t\tIAE$/\tIAE de Paris\tMBA\t/;
  s/\t\t\tIAE Paris$/\tIAE de Paris\tDESS\t/;
  s/\t\t\tActuaire CEA$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tActuaire IAF$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tActuaire qualifié$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tIAF$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tActuaire IAF-CEA$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tActuaire$/\tInstitut des Actuaires\tDipl.\t/;
  s/\t\t\tMBA Ctre de Perf aux Affaires$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tMBA Centre de Perfect aux Affaires$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tMBA Centre de Perfection aux Affaires$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tCPA$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tCPA 73\/2$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tMBA CPA$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tMBA CPA$/\tCPA de Paris\tMBA\t/;
  s/\t\t\tCPA Lyon$/\tCPA de Lyon\tMBA\t/;
  s/\t\t\tCPA Nord$/\tCPA du Nord\tMBA\t/;
  s/\t\t\tIHEDN$/\tIHEDN\tDipl.\t/;
  s/\t\t\tENA$/\tENA\tDipl.\t/;
  s/\t\t\tAncElENA$/\tENA\tDipl.\t/;
  s/\t\t\tDEA Economie EHESS-ENSAE$/\tEHESS\tDEA\tÉconomie/;
  s/\t\t\tDEA EHESS$/\tEHESS\tDEA\t/;
  s/\t\t\tDEA Sociologie EHESS$/\tEHESS\tDEA\t/;
  s/\t\t\tEHESS DEA$/\tEHESS\tDEA\t/;
  s/\t\t\tEHESS$/\tEHESS\tDEA\t/;
  s/\t\t\tMS EHESS$/\tEHESS\tMSc\t/;
  s/\t\t\tEHESS Master II Art & Langage$/\tEHESS\tM\tArt et Langage/;
  s/\t\t\tDoct3e cycle EHESS$/\tEHESS\tPhD\t/;
  s/\t\t\tDoct EHESS Sc cognitives$/\tEHESS\tPhD\tSciences cognitives/;
  s/\t\t\tEHESS : PhD$/\tEHESS\tPhD\t/;
  s/\t\t\tEHESS Phd$/\tEHESS\tPhD\t/;
  s/\t\t\tPhD EHESS$/\tEHESS\tPhD\t/;
  s/\t\t\tDoctorat HEC Finance$/\tHEC\tPhD\tFinance/;
  s/\t\t\tDESS CAAE Univ Paris I$/\tPanthéon-Sorbonne\tDESS\t/;
  s/\t\t\tDEA MMME Sorbonne$/\tPanthéon-Sorbonne\tDEA\tModélisation et Méthodes Mathématiques en Économie/;
  s/\t\t\tDEA MMME$/\tPanthéon-Sorbonne\tDEA\tModélisation et Méthodes Mathématiques en Économie/;
  s/\t\t\tDEA Sorbonne$/\tPanthéon-Sorbonne\tDEA\tModélisation et Méthodes Mathématiques en Économie/;
  s/\t\t\tDEA Univ Paris 1$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Panthéon-Sorbonne$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Paris 1 Modélisation Econ& Fin$/\tPanthéon-Sorbonne\tDEA\tModélisation Économie et finance/;
  s/\t\t\tDEA Univ Paris I$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Paris I$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA ScEcon Univ Paris I$/\tPanthéon-Sorbonne\tDEA\tÉconomie/;
  s/\t\t\tDEA Univ Paris 1er$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Univ Paris I Panthéon-Sorbonne$/\tPanthéon-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Economie Paris I$/\tPanthéon-Sorbonne\tDEA\tÉconomie/;
  s/\t\t\tMaster COSI Univ Paris I La Sorbonne$/\tPanthéon-Sorbonne\tM\tCOSI/;
  s/\t\t\tMS Univ Paris 1$/\tPanthéon-Sorbonne\tMSc\t/;
  s/\t\t\tMS Univ Paris I Panthéon Sorbonne$/\tPanthéon-Sorbonne\tMSc\t/;
  s/\t\t\tMSc Univ Paris I$/\tPanthéon-Sorbonne\tMSc\t/;
  s/\t\t\tMSc Finance Paris I$/\tPanthéon-Sorbonne\tMSc\tFinance/;
  s/\t\t\tPhD Univ Paris 1$/\tPanthéon-Sorbonne\tPhD\t/;
  s/\t\t\tPhD Univ 1$/\tPanthéon-Sorbonne\tPhD\t/;
  s/\t\t\tPhD Univ Paris I$/\tPanthéon-Sorbonne\tPhD\t/;
  s/\t\t\tMaitrise PhiloParis I$/\tPanthéon-Sorbonne\tMaîtr.\tPhilosophie/;
  s/\t\t\tHDR ScEco Univ Paris 1$/\tPanthéon-Sorbonne\tHDR\tÉconomie/;
  s/\t\t\tDESS Droit Paris 2$/\tAssas\tDESS\tDroit/;
  s/\t\t\tDESS Paris II Panthéon$/\tAssas\tDESS\t/;
  s/\t\t\tDEA Univ Paris 2$/\tAssas\tDEA\t/;
  s/\t\t\tDEA Univ Paris II Panthéon - Assas$/\tAssas\tDEA\t/;
  s/\t\t\tDEA Univ Paris II$/\tAssas\tDEA\t/;
  s/\t\t\tMS Univ Paris 2$/\tAssas\tMSc\t/;
  s/\t\t\tDEA Univ Paris IV$/\tParis-Sorbonne\tDEA\t/;
  s/\t\t\tDoct Paris IV Histoire Moderne$/\tParis-Sorbonne\tPhD\tHistoire Moderne/;
  s/\t\t\tDoctUnivParis IV$/\tParis-Sorbonne\tPhD\t/;
  s/\t\t\tPhD Univ Paris 4$/\tParis-Sorbonne\tPhD\t/;
  s/\t\t\tDEA Univ Paris V$/\tParis-Sorbonne\tDEA\t/;
  s/\t\t\tDEA Univ Paris 5$/\tParis-Sorbonne\tDEA\t/;
  s/\t\t\tDoctUnivParis V$/\tParis-Descartes\tPhD\t/;
  s/\t\t\tPhD Univ Paris V$/\tParis-Descartes\tPhD\t/;
  s/\t\t\tPhD Univ Paris 5$/\tParis-Descartes\tPhD\t/;
  s/\t\t\tDEA Univ Paris 6$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Univ Paris VI Jussieu$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA OJME Paris VI$/\tUPMC\t\tOJME/;
  s/\t\t\tDEA Univ Paris VI$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Probabilités Paris VI$/\tUPMC\tDEA\tProbabilités/;
  s/\t\t\tDEA Paris VI$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Univ Paris 6 Jussieu$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Jussieu$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Finance Univ Paris VI$/\tUPMC\tDEA\tFinance/;
  s/\t\t\tDEA Univ Paris 6$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Algorithmique Univ Paris VI$/\tUPMC\tDEA\tAlgorithmique/;
  s/\t\t\tDEA Paris VI Finance$/\tUPMC\tDEA\tFinance/;
  s/\t\t\tDEA Probab & Applications Paris 6$/\tUPMC\tDEA\tProbabilités et applications/;
  s/\t\t\tDEA Stat Univ Paris 6$/\tUPMC\tDEA\tStatistiques/;
  s/\t\t\tDEA Paris 6$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA univ Paris VI$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Probabilités et Finance Paris VI$/\tUPMC\tDEA\tProbabilités et Finance/;
  s/\t\t\tDEA Sc des Matériaux Paris VI$/\tUPMC\tDEA\tSciences des matériaux/;
  s/\t\t\tDEA IARFAG Paris VI$/\tUPMC\tDEA\tIARFAG/;
  s/\t\t\tDEA IARFAG$/\tUPMC\tDEA\tIARFAG/;
  s/\t\t\tDEA d'Analyse numérique Paris VI$/\tUPMC\tDEA\tAnalyse numérique/;
  s/\t\t\tDEA Paris VI Pierre & Marie Curie$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Univ Paris VI Pierre et Marie Curie$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Univ ParisVI Proba & Finance$/\tUPMC\tDEA\tProbabilités et Finance/;
  s/\t\t\tDEA Univ Paris VI Jussieu-Curie$/\tUPMC\tDEA\t/;
  s/\t\t\tDEA Univ Paris VI Pierre & Marie Curie$/\tUPMC\tDEA\t/;
  s/\t\t\tM2 Mathématiques Fondamentales Paris VI$/\tUPMC\tMSc\tMathématiques Fondamentales/;
  s/\t\t\tMSc 2 Proba & Finance Paris VI$/\tUPMC\tDEA\tProbabilités et Finance/;
  s/\t\t\tMSc Univ Paris VI$/\tUPMC\tMSc\t/;
  s/\t\t\tMSc Univ Paris VI Pierre et Marie Curie$/\tUPMC\tMSc\t/;
  s/\t\t\tMS Univ Paris 6$/\tUPMC\tMSc\t/;
  s/\t\t\tMS Univ Paris VI$/\tUPMC\tMSc\t/;
  s/\t\t\tMS Univ Paris V P & M Curie$/\tUPMC\tMSc\t/;
  s/\t\t\tMS Univ Paris VI Pierre & Marie Curie$/\tUPMC\tMSc\t/;
  s/\t\t\tDoctUnivParis VI en Ecologie$/\tUPMC\tPhD\tÉcologie/;
  s/\t\t\tDoct Chimie Univ Paris VI$/\tUPMC\tPhD\tChimie/;
  s/\t\t\tDoctUnivParis VI$/\tUPMC\tPhD\t/;
  s/\t\t\tDoctès Sc Informatique\/Micro-électronique Univ Paris VI$/\tUPMC\tPhD\tInformatique Micro-électronique/;
  s/\t\t\tDocten Informatique \- Paris 6$/\tUPMC\tPhD\tInformatique/;
  s/\t\t\tDoct UnivParis VI$/\tUPMC\tPhD\t/;
  s/\t\t\tDoctUnivParis VI Physique quantique$/\tUPMC\tPhD\tPhysique quantique/;
  s/\t\t\tDoct Univ Paris VI$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Jussieu$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Jussieu$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ Paris 6$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ Paris VI$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ paris VI$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ de Paris$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ Paris 6 Jussieu$/\tUPMC\tPhD\t/;
  s/\t\t\tPhD Univ Paris Jussieu$/\tUPMC\tPhD\t/;
  s/\t\t\tHdR Univ Paris 6$/\tUPMC\tHDR\t/;
  s/\t\t\tHDR Paris VI$/\tUPMC\tHDR\t/;
  s/\t\t\tThèse Biologie Paris VI$/\tUPMC\tPhD\tBiologie/;
  s/\t\t\tThèse d'Univ Paris VI$/\tUPMC\tPhD\t/;
  s/\t\t\tThèse Paris 6 neurosciences$/\tUPMC\tPhD\tNeurosciences/;
  s/\t\t\tThése UnivParis VI SpécPhysique des Solides$/\tUPMC\tPhD\tPhysique des Solides/;
  s/\t\t\tDEUG Japonais Paris VII$/\tParis-Diderot\tDEUG\tJaponnais/;
  s/\t\t\tDEA Univ Paris 7$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tDEA Télédétection Paris VII$/\tParis-Diderot\tDEA\tTélédétection/;
  s/\t\t\tDEA Jussieu Paris 7$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tDEA Univ Paris VII$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tDEA univ Paris VII$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tDEA Univ Paris 7 Denis Diderot-Jussieu$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tDEA Math Appliquées Paris VII$/\tParis-Diderot\tDEA\tMathématiques appliquées/;
  s/\t\t\tDEA Sociologie Univ Paris VII$/\tParis-Diderot\tDEA\tSociologie/;
  s/\t\t\tDEA Univ paris VII Diderot-Jussieu$/\tParis-Diderot\tDEA\t/;
  s/\t\t\tMSc Univ Paris VII$/\tParis-Diderot\tMSc\t/;
  s/\t\t\tMS Univ Paris VII$/\tParis-Diderot\tMSc\t/;
  s/\t\t\tDoctUnivParis VII$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tDoct Physique des Solides Univ Paris VII$/\tParis-Diderot\tPhD\tPhysique des Solides/;
  s/\t\t\tDoct3È Cycle Univ Paris 7$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tThèse de DoctUnivParis VII$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tPhD Univ Paris 7$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tPhD Univ Paris 7$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tPhD Univ Paris VII$/\tParis-Diderot\tPhD\t/;
  s/\t\t\tPhD Univ Paris 8$/\tVincennes-Saint-Denis\tPhD\t/;
  s/\t\t\tMBA Dauphine$/\tDauphine\tMBA\t/;
  s/\t\t\tDESS Paris Dauphine$/\tDauphine\tDESS\t/;
  s/\t\t\tDESS Dauphine$/\tDauphine\tDESS\t/;
  s/\t\t\tDESS Gestion Publique Paris Dauphine$/\tDauphine\tDESS\tGestion Publique/;
  s/\t\t\tDEA Dauphine$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA Univ Paris Dauphine$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA ScEcon Paris Dauphine$/\tDauphine\tDEA\tÉconomie/;
  s/\t\t\tDEA Economie Ind Univ Paris IX$/\tDauphine\tDEA\tÉconomie/;
  s/\t\t\tDEA univ Paris IX Dauphine$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA ANLA Paris IX$/\tDauphine\tDEA\tANLA/;
  s/\t\t\tDEA Univ Paris IX Dauphine$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA Univ Paris 9$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA Economie Paris Dauphine$/\tDauphine\tDEA\tÉconomie/;
  s/\t\t\tDEA Economie ind Paris IX$/\tDauphine\tDEA\tÉconomie/;
  s/\t\t\tDEA Economie Ind Paris Dauphine$/\tDauphine\tDEA\tÉconomie/;
  s/\t\t\tDEA Univ Paris IX$/\tDauphine\tDEA\t/;
  s/\t\t\tDEA Paris Dauphine$/\tDauphine\tDEA\t/;
  s/\t\t\tMSc Univ Paris IX$/\tDauphine\tMSc\t/;
  s/\t\t\tDoctUniv Paris IX$/\tDauphine\tPhD\t/;
  s/\t\t\tDoctUnivParis Dauphine$/\tDauphine\tPhD\t/;
  s/\t\t\tDoctUnivParis IX$/\tDauphine\tPhD\t/;
  s/\t\t\tPhD Univ Paris Dauphine$/\tDauphine\tPhD\t/;
  s/\t\t\tPhD Univ Paris 9$/\tDauphine\tPhD\t/;
  s/\t\t\tPhD Dauphine$/\tDauphine\tPhD\t/;
  s/\t\t\tPhD Univ Paris IX$/\tDauphine\tPhD\t/;
  s/\t\t\tPhD univ Paris IX$/\tDauphine\tPhD\t/;
  s/\t\t\tDEA Univ Paris 10$/\tNanterre\tDEA\t/;
  s/\t\t\tMS Univ Paris 10 Nanterre$/\tNanterre\tDEA\t/;
  s/\t\t\tDEA Univ Paris X$/\tNanterre\tDEA\t/;
  s/\t\t\tMaster II d'Economie Univ Paris X$/\tNanterre\tM\tÉconomie/;
  s/\t\t\tDocten Sc Univ Paris X$/\tNanterre\tPhD\t/;
  s/\t\t\tDoct Univ Paris X$/\tNanterre\tPhD\t/;
  s/\t\t\tPhD Univ Paris X Philo Esthétique$/\tNanterre\tPhD\tPhilosophie/;
  s/\t\t\tDEA Orsay$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA ATS Orsay$/\tParis-Sud\tDEA\tATS/;
  s/\t\t\tDEA Univ Paris 11$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Univ Paris XI Physdes Solides$/\tParis-Sud\tDEA\tPhysique des solides/;
  s/\t\t\tDEA UnivParis 11$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Univ Paris XI$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Univ Paris XI Orsay$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Paris 11 Orsay$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Univ Paris Orsay$/\tParis-Sud\tDEA\t/;
  s/\t\t\tDEA Univ Paris 11 Orsay$/\tParis-Sud\tDEA\t/;
  s/\t\t\tMaster Univ Paris 11$/\tParis-Sud\tM\t/;
  s/\t\t\tMSc Univ Paris XI$/\tParis-Sud\tMSc\t/;
  s/\t\t\tMSc Univ Paris 11 Orsay$/\tParis-Sud\tMSc\t/;
  s/\t\t\tMSc UNiv Paris XI$/\tParis-Sud\tMSc\t/;
  s/\t\t\tDoctUnivParis XI$/\tParis-Sud\tPhD\t/;
  s/\t\t\tDocten Physique XI$/\tParis-Sud\tPhD\tPhysique/;
  s/\t\t\tDoct de Physique UnivParis XI$/\tParis-Sud\tPhD\tPhysique/;
  s/\t\t\tDoct Physique Solide Paris XI$/\tParis-Sud\tPhD\tPhysique du Solide/;
  s/\t\t\tDoct Univers Paris Sud$/\tParis-Sud\tPhD\t/;
  s/\t\t\tDoctUnivParis XI Electronique$/\tParis-Sud\tPhD\tÉlectronique/;
  s/\t\t\tDoct d'écologie Paris XI$/\tParis-Sud\tPhD\tÉcologie/;
  s/\t\t\tDoct Univ Paris XI$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Univ Paris 11$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Univ paris 11$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Univ Paris XI$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Orsay$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Orsay$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Physique Paris XI$/\tParis-Sud\tPhD\tPhysique/;
  s/\t\t\tPhD Paris XI$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Univ Paris 11 Orsay$/\tParis-Sud\tPhD\t/;
  s/\t\t\tPhD Univ Paris 11 Orsay$/\tParis-Sud\tPhD\t/;
  s/\t\t\tDEA Univ Paris 12$/\tParis-Val de Marne\tDEA\t/;
  s/\t\t\tDEA UnivParis 12 Val de Marne$/\tParis-Val de Marne\tDEA\t/;
  s/\t\t\tDEA Univ Paris XII$/\tParis-Val de Marne\tDEA\t/;
  s/\t\t\tMaster en Urbanisme IUP Paris XII$/\tParis-Val de Marne\tMUP\tUrbanisme/;
  s/\t\t\tMSc Univ Paris XII$/\tParis-Val de Marne\tMSc\t/;
  s/\t\t\tDoctUnivParis XII$/\tParis-Val de Marne\tPhD\t/;
  s/\t\t\tDocten Droit des Affaires Univ Paris 12$/\tParis-Val de Marne\tPhD\tDroit des Affaires/;
  s/\t\t\tPhD Univ Paris 12$/\tParis-Val de Marne\tPhD\t/;
  s/\t\t\tPhD Univ Paris XII$/\tParis-Val de Marne\tPhD\t/;
  s/\t\t\tDoctUnivParis-Nord$/\tParis-Nord\tPhD\t/;
  s/\t\t\tPhD Univ Paris 13$/\tParis-Nord\tPhD\t/;
  s/\t\t\tPhD Univ Paris XIII$/\tParis-Nord\tPhD\t/;
  s/\t\t\tThèse de Paris XIII Mathématiques$/\tParis-Nord\tPhD\tMathématiques/;
  s/\t\t\tDoctUnivPSabatier$/\tUniversité Paul-Sabatier\tPhD\t/;
  s/\t\t\tMSc Univ Toulouse III$/\tUniversité Paul-Sabatier\tMSc\t/;
  s/\t\t\tDoct Univ Toulouse III$/\tUniversité Paul-Sabatier\tPhD\t/;
  s/\t\t\tPhD Univ Paul Sabatier Toulouse$/\tUniversité Paul-Sabatier\tPhD\t/;
  s/\t\t\tPhD Univ Toulouse III$/\tUniversité Paul-Sabatier\tPhD\t/;
  s/\t\t\tMSc Univ Grenoble I$/\tUJF\tMSc\t/;
  s/\t\t\tDEA Informatique Univ de Grenoble$/\tUJF\tDEA\tInformatique/;
  s/\t\t\tDoctUnivGrenoble$/\tUJF\tPhD\t/;
  s/\t\t\tPhD Grenoble$/\tUJF\tPhD\t/;
  s/\t\t\tDoctUnivLyon I$/\tUniversité Claude Bernard\tPhD\t/;
  s/\t\t\tDoct Univ Lyon I$/\tUniversité Claude Bernard\tPhD\t/;
  s/\t\t\tDoct Université Lyon I$/\tUniversité Claude Bernard\tPhD\t/;
  s/\t\t\tDESGE Lyon III$/\tUniversité Jean-Moulin\tDESS\tDESGE/;
  s/\t\t\tDoct Aix Marseille II$/\tUniversité de la Méditerranée\tPhD\t/;
  s/\t\t\tDoctUnivde Rennes$/\tUniversité de Rennes 1\tPhD\t/;
  s/\t\t\tLic Théologie & Sc des religions Univ Strasbourg$/\tUDS\tLic.\tThéologie Science des religion/;
  s/\t\t\tDoct Univ Strasbourg$/\tUDS\tPhD\t/;
  s/\t\t\tDocten Informatique et Applications de l'Univ de Caen$/\tUCBN\tPhD\tInformatique/;
  s/\t\t\tDEA IGP Bordeaux$/\tUniversité de Bordeaux\tDEA\tIGP/;
  s/\t\t\tHDR UBO$/\tUBO\tHDR\t/;
  s/\t\t\tThèse UTC$/\tUTC\tPhD\t/;
  s/\t\t\tMBA Institut Européen d'Administration des Affaires$/\tINSEAD\tMBA\t/;
  s/\t\t\tMBA Inst Europ d'Adm des Aff$/\tINSEAD\tMBA\t/;
  s/\t\t\tINSEAD : MBA$/\tINSEAD\tMBA\t/;
  s/\t\t\tEDP\/INSEAD$/\tINSEAD\tMBA\tEDP/;
  s/\t\t\tPSD INSEAD$/\tINSEAD\tMBA\tPSD/;
  s/\t\t\tINSEAD - AMP$/\tINSEAD\tMBA\tAMP/;
  s/\t\t\tMBA INSEAD$/\tINSEAD\tMBA\t/;
  s/\t\t\tINSEAD$/\tINSEAD\tMBA\t/;
  s/\t\t\tScPo Gestion et Stratégie des Entreprises$/\tSciences Po\tDipl.\tGestion et Stratégie des Entreprises/;
  s/\t\t\tScPo Economie$/\tSciences Po\tDipl.\tÉconomie/;
  s/\t\t\tIEP$/\tSciences Po\tDipl.\t/;
  s/\t\t\tIEP de Paris$/\tSciences Po\tDipl.\t/;
  s/\t\t\tIEP Paris$/\tSciences Po\tDipl.\t/;
  s/\t\t\tLauréat IEP$/\tSciences Po\tDipl.\t/;
  s/\t\t\tScPo$/\tSciences Po\tDipl.\t/;
  s/\t\t\tScPo Paris$/\tSciences Po\tDipl.\t/;
  s/\t\t\tDEA IEP Paris$/\tSciences Po\tDEA\t/;
  s/\t\t\tMS IEP Paris$/\tSciences Po\tMSc\t/;
  s/\t\t\tMS IEP$/\tSciences Po\tMSc\t/;
  s/\t\t\tMSc IEP$/\tSciences Po\tMSc\t/;
  s/\t\t\tEAPB Ecole Architecture Paris Belleville$/\tENSAPB\tDipl.\t/;
  s/\t\t\tEAPLV Ecole Architecture Paris La Villette$/\tENSAPLV\tDipl.\t/;
  s/\t\t\tEAVT Ecole d'Architecture de Marne la vallée$/\tEAVT\tDipl.\t/;
  s/\t\t\tEAVT Ecole d'architecture de Marne La Vallée$/\tEAVT\tDipl.\t/;
  s/\t\t\tEAVT Ecole d'Architecture de Marne la Vallée$/\tEAVT\tDipl.\t/;
  s/\t\t\tCESB Paris$/\tCFPB\tDipl.\tCESB/;
  s/\t\t\tCESB$/\tCFPB\tDipl.\tCESB/;
  s/\t\t\tCEPE$/\tCEPE\tDipl.\t/;
  s/\t\t\tCEPE Ecole Pratique des Hautes Etudes$/\tCEPE\tDipl.\t/;
  s/\t\t\tECE$/\tECE\tIng.\t/;
  s/\t\t\tCHEAR$/\tCHEAr\tDipl.\t/;
  s/\t\t\tCHEA$/\tCHEAr\tDipl.\t/;
  s/\t\t\tIHEDN-CHEAR$/\tCHEAr\tDipl.\tIHEDN/;
  s/\t\t\tDocCHEA$/\tCHEAr\tPhD\t/;
  s/\t\t\tISA$/\tISA\tDipl.\t/;
  s/\t\t\tInstitut Supérieur des Affaires$/\tISA\tDipl.\t/;
  s/\t\t\tISAA$/\tISAA\tDipl.\t/;
  s/\t\t\tCentre des Hautes Etudes de la Construction$/\tCHEC\tDipl.\t/;
  s/\t\t\tCHEC$/\tCHEC\tDipl.\t/;
  s/\t\t\tCHEBAP$/\tCHEC\tDipl.\tCHEBAP/;
  s/\t\t\tHEC$/\tHEC\tM\t/;
  s/\t\t\tMBA HEC$/\tHEC\tMBA\t/;
  s/\t\t\tMS Marketing HEC$/\tHEC\tMSc\tMarketing/;
  s/\t\t\tHEC : MBA$/\tHEC\tMBA\t/;
  s/\t\t\tMS HEC$/\tHEC\tMSc\t/;
  s/\t\t\tCESA Achats HEC Management$/\tHEC\tM\tCESA Achats Management/;
  s/\t\t\tMS X-HEC$/\tHEC\tMSc\t/;
  s/\t\t\tHEC Master Gestion du Changement$/\tHEC\tM\tGestion du Changement/;
  s/\t\t\tHEC-Entrepreneurs$/\tHEC\tM\tEntrepreneurs/;
  s/\t\t\tMaster HEC Entrepreneurs$/\tHEC\tM\tEntrepreneurs/;
  s/\t\t\tMSc HEC$/\tHEC\tMSc\t/;
  s/\t\t\tHEC : MS$/\tHEC\tMSc\t/;
  s/\t\t\tMaster HEC Finance$/\tHEC\tM\tFinance/;
  s/\t\t\tMS X-HEC Finance$/\tHEC\tMSc\tFinance/;
  s/\t\t\tMBA CPA-HEC$/\tHEC\tMBA\tCPA/;
  s/\t\t\tExecutive MBA HEC$/\tHEC\tMBA\t/;
  s/\t\t\tMastère Gestion Financière HEC$/\tHEC\tM\tGestion Financière/;
  s/\t\t\tMBA HEC\/CPA$/\tHEC\tMBA\t/;
  s/\t\t\tHEC Entrepreneurs$/\tHEC\tM\tEntrepreneurs/;
  s/\t\t\tHEC Execut Management \/ CPA$/\tHEC\tMBA\t/;
  s/\t\t\tMSc HEC Start Management$/\tHEC\tMSc\tManagement/;
  s/\t\t\tCEIPI$/\tCEIPI\tDipl.\t/;
  s/\t\t\tCEDEP cycle 43$/\tCEDEP\tDipl.\t/;
  s/\t\t\tCEDEP$/\tCEDEP\tDipl.\t/;
  s/\t\t\tEPNER$/\tEPNER\tDipl.\t/;
  s/\t\t\tIFSBM$/\tIFSBM\tDipl.\t/;
  s/\t\t\tESG$/\tESG Paris\tDipl.\t/;
  s/\t\t\tMBA ESCP$/\tESCP-EAP\tMBA\t/;
  s/\t\t\tMBA ESCP-EAP$/\tESCP-EAP\tMBA\t/;
  s/\t\t\tMBA ESCP EAP$/\tESCP-EAP\tMBA\t/;
  s/\t\t\tExecutive MBA ESCP-EAP$/\tESCP-EAP\tMBA\t/;
  s/\t\t\tESCP-EAP$/\tESCP-EAP\tMBA\t/;
  s/\t\t\tSTEGE MGT GENERAL ESCP-EAP$/\tESCP-EAP\tMBA\tSTEGE MGT GENERAL/;
  s/\t\t\tESCP-EAP Executive MS Ingénierie financière et fiscale$/\tESCP-EAP\tMSc\tIngénierie financière et fiscale/;
  s/\t\t\tMBA ESSEC$/\tESSEC\tMBA\t/;
  s/\t\t\tMBA Essec$/\tESSEC\tMBA\t/;
  s/\t\t\tESSEC Management général$/\tESSEC\tMBA\tManagement général/;
  s/\t\t\tESSEC$/\tESSEC\tMBA\t/;
  s/\t\t\tEMBA ESSEC$/\tESSEC\tMBA\t/;
  s/\t\t\tMBA ESSEC-MANNHEIM$/\tESSEC\tMBA\t/;
  s/\t\t\tESSEC Mastère Tehniques Financières$/\tESSEC\tM\tTehniques Financières/;
  s/\t\t\tESSEC Management Général$/\tESSEC\tMBA\tManagement général/;
  s/\t\t\tCtre de FormJournaliste$/\tCFJ\tDipl.\t/;
  s/\t\t\tEcole Nationale de la Magistrature$/\tENM\tDipl.\t/;
  s/\t\t\tDESIA$/\tISAE\tDipl.\tDESIA/;
  s/\t\t\tIHEDN 26° session$/\tIHEDN\tDipl.\t/;
  s/\t\t\tIHEE$/\tIHEE\tDipl.\t/;
  s/\t\t\tEcole de l'Air$/\tÉcole de l'Air\tDipl.\t/;
  s/\t\t\tIHESI$/\tINHES\tDipl.\t/;
  s/\t\t\tAFITEP$/\tAFITEP\tDipl.\t/;

  # Foreign universities.
  s/\t\t\tMS MIT$/\tMIT\tMSc\t/;
  s/\t\t\tMBA MIT$/\tMIT\tMBA\t/;
  s/\t\t\tMS MIT TPP$/\tMIT\tMSc\tTTP/;
  s/\t\t\tNA MIT$/\tMIT\tMA\t/;
  s/\t\t\tMS Computer ScMIT$/\tMIT\tMSc\tInfomatique/;
  s/\t\t\tMS TechnoPolicy MIT$/\tMIT\tMSc\tTechnology and Policy/;
  s/\t\t\tMIT Chemical Engineering$/\tMIT\tMSc\tChemical Engineering/;
  s/\t\t\tMBA MIT Sloan School of Management$/\tMIT\tMBA\tSloan School of Management/;
  s/\t\t\tUniv MIT$/\tMIT\tM\t/;
  s/\t\t\tMS "Technology & Policy" MIT$/\tMIT\tMSc\tTechnology and Policy/;
  s/\t\t\tMS MIT Nuclear Eng$/\tMIT\tMSc\tNuclear Engineering/;
  s/\t\t\tMS MITof Transportation$/\tMIT\tMSc\tTransportation/;
  s/\t\t\tMS Massachusetts Institute of Techn$/\tMIT\tMSc\t/;
  s/\t\t\tMS Massachusetts Institute of Technology$/\tMIT\tMSc\t/;
  s/\t\t\tMS Massachusetts$/\tMIT\tMSc\t/;
  s/\t\t\tMS Massachusetts Inst of Tech$/\tMIT\tMSc\t/;
  s/\t\t\tMS Massuchusetts Institute of Technology$/\tMIT\tMSc\t/;
  s/\t\t\tMS Massachusetts Inst of Technology$/\tMIT\tMSc\t/;
  s/\t\t\tMBA Massachusetts Institute of Technology$/\tMIT\tMBA\t/;
  s/\t\t\tDoct MIT$/\tMIT\tPhD\t/;
  s/\t\t\tPhD MIT$/\tMIT\tPhD\t/;
  s/\t\t\tPhD MIT Finance$/\tMIT\tPhD\tFinance/;
  s/\t\t\tPhD Massachusetts Institute of Technology$/\tMIT\tPhD\t/;
  s/\t\t\tPhD Massachusetts Institute of Technology$/\tMIT\tPhD\t/;
  s/\t\t\tPhD Massachusetts$/\tMIT\tPhD\t/;
  s/\t\t\tPhD Massachusetts Inst of Technology$/\tMIT\tPhD\t/;
  s/\t\t\tPhD MIT Engineering Systems$/\tMIT\tPhD\tIngénierie/;
  s/\t\t\tIMI Harvard$/\tHarvard\tM\tIMI/;
  s/\t\t\tUniv Harvard AMP$/\tHarvard\tM\tAMP/;
  s/\t\t\tAMP Harvard 99$/\tHarvard\tM\tAMP 99/;
  s/\t\t\tMBA Harvard Business School$/\tHarvard\tMBA\t/;
  s/\t\t\tHarvard Business Sch Alumnus$/\tHarvard\tMBA\t/;
  s/\t\t\tExecutive Education, Harvard Business School$/\tHarvard\tMBA\t/;
  s/\t\t\tMPA Univ Harvard$/\tHarvard\tMPA\t/;
  s/\t\t\tAdvanced Manag Program Harvard$/\tHarvard\tMBA\t/;
  s/\t\t\tM A Harvard$/\tHarvard\tMA\t/;
  s/\t\t\tMS Harvard$/\tHarvard\tMSc\t/;
  s/\t\t\tMBA Harvard$/\tHarvard\tMBA\t/;
  s/\t\t\tPhD Harvard$/\tHarvard\tPhD\t/;
  s/\t\t\tPhD Univ Harvard$/\tHarvard\tPhD\t/;
  s/\t\t\tPhD Univ Havard$/\tHarvard\tPhD\t/;
  s/\t\t\tPhD Harvard Economie$/\tHarvard\tPhD\tÉconomie/;
  s/\t\t\tPhD Applied Mathematics Havard University$/\tHarvard\tPhD\tMathématiques appliquées/;
  s/\t\t\tMS Purdue$/\tPurdue University\tMSc\t/;
  s/\t\t\tMBA Purdue$/\tPurdue University\tMBA\t/;
  s/\t\t\tPhD Purdue$/\tPurdue University\tPhD\t/;
  s/\t\t\tDoctd'ArchitectUniversRome$/\tUniversity of Rome\tPhD\tArchitecture/;
  s/\t\t\tMSc Univ ETH Zurich$/\tETH Zürich\tMSc\t/;
  s/\t\t\tMSc Eidgenossische Tech Hochschule Zurich$/\tETH Zürich\tMSc\t/;
  s/\t\t\tMSc Eidgenossische Tech Hochschule Zurich$/\tETH Zürich\tMSc\t/;
  s/\t\t\tMSc ETH Zürich$/\tETH Zürich\tMSc\t/;
  s/\t\t\tMSc Eidgenössische Technische Hochschule Zürich$/\tETH Zürich\tMSc\t/;
  s/\t\t\tDoctEcPolytZurich$/\tETH Zürich\tPhD\t/;
  s/\t\t\tDoct Eidgenössische Technische Hochschule Zürich$/\tETH Zürich\tPhD\t/;
  s/\t\t\tMS Univ Zürich$/\tUniversität Zürich\tMSc\t/;
  s/\t\t\tDoct Univ Zurich$/\tUniversität Zürich\tPhD\t/;
  s/\t\t\tIng EP Fédérale Lausanne$/\tEPFL\tIng.\t/;
  s/\t\t\tIng Ecole Polytechnique Lausanne$/\tEPFL\tIng.\t/;
  s/\t\t\tIng EP Lausanne$/\tEPFL\tIng.\t/;
  s/\t\t\tMSc Ecole polytechnique fédérale de Lausanne$/\tEPFL\tMSc\t/;
  s/\t\t\tEP Fédérale Lausanne$/\tEPFL\tM\t/;
  s/\t\t\tcycle postgrade EPFL option Finance$/\tEPFL\tM\tFinance/;
  s/\t\t\tEPFL Génie Mécanique$/\tEPFL\tM\t/;
  s/\t\t\tDoct Ecole polytechnique fédérale de Lausanne$/\tEPFL\tPhD\t/;
  s/\t\t\tPhD Univ Lausanne$/\tUNIL\tPhD\t/;
  s/\t\t\tMBA Institute for Management Development$/\tIMD\tMBA\t/;
  s/\t\t\tIMD Lausanne$/\tIMD\tMBA\t/;
  s/\t\t\tMBA IMD$/\tIMD\tMBA\t/;
  s/\t\t\tMS Pennsylvania$/\tPennsylvania State University\tMSc\t/;
  s/\t\t\tDoct Pennsylvania State Univ$/\tPennsylvania State University\tPhD\t/;
  s/\t\t\tM Eng Yale$/\tYale\tMEng\t/;
  s/\t\t\tMS Yale$/\tYale\tMSc\t/;
  s/\t\t\tMS Yale Environmental Health$/\tYale\tMSc\tEnvironmental Health/;
  s/\t\t\tPhD Yale$/\tYale\tPhD\t/;
  s/\t\t\tPhD Univ Yale$/\tYale\tPhD\t/;
  s/\t\t\tMS Wisconsin USA$/\tUW-Madison\tMSc\t/;
  s/\t\t\tMBA Univ Wisconsin-Madison$/\tUW-Madison\tMBA\t/;
  s/\t\t\tMS Wisconsin Madison$/\tUW-Madison\tMSc\t/;
  s/\t\t\tPhD Wisconsin$/\tUW-Madison\tPhD\t/;
  s/\t\t\tMS Berkeley$/\tBerkeley\tMSc\t/;
  s/\t\t\tMEcoUcBerkeley$/\tBerkeley\tME\t/;
  s/\t\t\tMEcoAgricBerkeley$/\tBerkeley\tME\t/;
  s/\t\t\tUC Berkeley$/\tBerkeley\tM\t/;
  s/\t\t\tMCP Berkeley$/\tBerkeley\tMCP\t/;
  s/\t\t\tMCityPlann Berkeley$/\tBerkeley\tMCP\t/;
  s/\t\t\tMBA Berkeley$/\tBerkeley\tMBA\t/;
  s/\t\t\tMS UC Berkeley$/\tBerkeley\tMSc\t/;
  s/\t\t\tME Univ Berkeley$/\tBerkeley\tME\t/;
  s/\t\t\tManag of Technology Berkeley$/\tBerkeley\tM\tManagement/;
  s/\t\t\tMSc en Ingenierie Nucléaire à l'Université de Berkeley, Californie$/\tBerkeley\tMSc\tIngenierie Nucléaire/;
  s/\t\t\tPhD Berkeley$/\tBerkeley\tPhD\t/;
  s/\t\t\tMS Michigan$/\tMichigan\tMSc\t/;
  s/\t\t\tMBA Michigan$/\tMichigan\tMBA\t/;
  s/\t\t\tMaster of Eng in Manufacturing \- U of Michigan$/\tMichigan\tMEng\tManufacturing/;
  s/\t\t\tME Univ Michigan$/\tMichigan\tME\t/;
  s/\t\t\tMSc Michigan$/\tMichigan\tMSc\t/;
  s/\t\t\tPhD Michigan$/\tMichigan\tPhD\t/;
  s/\t\t\tStanford$/\tStanford\tM\t/;
  s/\t\t\tStanford SEP$/\tStanford\tM\tSEP/;
  s/\t\t\tMS Informatique Stanford$/\tStanford\tMSc\tInformatique/;
  s/\t\t\tMS Stanford Engin Management$/\tStanford\tMSc\tEngin Management/;
  s/\t\t\tMasters of Electrical Engineering, Stanford$/\tStanford\tMSc\tElectrical Engineering/;
  s/\t\t\tMS Stanford Chemical Eng$/\tStanford\tMSc\tChemical Engeneering/;
  s/\t\t\tMS Management a Stanford$/\tStanford\tMSc\tManagement/;
  s/\t\t\tME Univ Stanford$/\tStanford\tME\t/;
  s/\t\t\tMS Stanford en Electrical Engineering$/\tStanford\tMSc\tElectrical Engineering/;
  s/\t\t\tMSEE Stanford$/\tStanford\tMSc\tElectrical Engineering/;
  s/\t\t\tMS of Science Stanford$/\tStanford\tMSc\t/;
  s/\t\t\tMS Electrical Eng Stanford$/\tStanford\tMSc\tElectrical Engineering/;
  s/\t\t\tStanford Executive Program$/\tStanford\tM\t/;
  s/\t\t\tSEP Stanford Univ$/\tStanford\tM\tSEP/;
  s/\t\t\tMBA Univ Stanford$/\tStanford\tMBA\t/;
  s/\t\t\tMS&E Stanford$/\tStanford\tMSc\t/;
  s/\t\t\tStanford University$/\tStanford\tM\t/;
  s/\t\t\tME Univ Stanford$/\tStanford\tME\t/;
  s/\t\t\tMS Stanford$/\tStanford\tMSc\t/;
  s/\t\t\tMBA Stanford$/\tStanford\tMBA\t/;
  s/\t\t\tPhD Stanford$/\tStanford\tPhD\t/;
  s/\t\t\tPhD Univ Stanford$/\tStanford\tPhD\t/;
  s/\t\t\tPhD EconomStanford$/\tStanford\tPhD\tÉconomie/;
  s/\t\t\tMS Cambridge$/\tCambridge\tMSc\t/;
  s/\t\t\tMphil Cambridge$/\tCambridge\tMPhil\t/;
  s/\t\t\tPhD Cambridge$/\tCambridge\tPhD\t/;
  s/\t\t\tPhD Univ Cambridge$/\tCambridge\tPhD\t/;
  s/\t\t\tMBA Wharton$/\tThe Wharton School\tMBA\t/;
  s/\t\t\tPhD Pennsylvania Wharton$/\tThe Wharton School\tPhD\t/;
  s/\t\t\tPhD Cleveland$/\tCSU\tPhD\t/;
  s/\t\t\tPhDManagVanderblit$/\tVanderbilt University\tPhD\tManagement/;
  s/\t\t\tPhD Salt Lake City$/\tUniversity of Utah\tPhD\t/;
  s/\t\t\tBA Univ Cornell$/\tCornell\tBA\t/;
  s/\t\t\tMS Cornell NY$/\tCornell\tMSc\t/;
  s/\t\t\tMBA Cornell University$/\tCornell\tMBA\t/;
  s/\t\t\tM Eng Cornell University$/\tCornell\tMEng\t/;
  s/\t\t\tME Univ Cornell$/\tCornell\tME\t/;
  s/\t\t\tPhD Cornell Ithaca$/\tCornell\tPhD\t/;
  s/\t\t\tMS Computer ScUcla$/\tUCLA\tMSc\tInformatique/;
  s/\t\t\tMBA HEC\/Ucla$/\tUCLA\tMBA\t/;
  s/\t\t\tMS Ucla$/\tUCLA\tMSc\t/;
  s/\t\t\tMS Univ UCLA$/\tUCLA\tMSc\t/;
  s/\t\t\tMBA UCLA Anderson$/\tUCLA\tMBA\t/;
  s/\t\t\tMSc UCLA$/\tUCLA\tMSC\t/;
  s/\t\t\tMS UCLA$/\tUCLA\tMSc\t/;
  s/\t\t\tPhD Los Angeles$/\tUCLA\tPhD\t/;
  s/\t\t\tPhD University of California$/\tUCLA\tPhD\t/;
  s/\t\t\tMSc Univ de Californie$/\tUCLA\tMSc\t/;
  s/\t\t\tPhD UCLA$/\tUCLA\tPhD\t/;
  s/\t\t\tPhD Univ UCLA$/\tUCLA\tPhD\t/;
  s/\t\t\tMS Colorado$/\tCU\tMSc\t/;
  s/\t\t\tPhD Colorado$/\tCU\tPhD\t/;
  s/\t\t\tColorado school of Mines$/\tColorado School of Mines\tM\t/;
  s/\t\t\tMS Colorado School of Mines$/\tColorado School of Mines\tMSc\t/;
  s/\t\t\tMS Colorado Scholl of MInes$/\tColorado School of Mines\tMSc\t/;
  s/\t\t\tMS Austin$/\tUT Austin\tMSc\t/;
  s/\t\t\tPhD Austin$/\tUT Austin\tPhD\t/;
  s/\t\t\tPhD Univ Texas$/\tUT Austin\tPhD\t/;
  s/\t\t\tMS Santa Barbara$/\tUCSB\tMSc\t/;
  s/\t\t\tPhD Santa Barbara$/\tUCSB\tPhD\t/;
  s/\t\t\tPhD Virginia Tech$/\tVirginia Tech\tPhD\t/;
  s/\t\t\tPhD Pennsylvania$/\tUniversity of Pennsylvania\tPhD\t/;
  s/\t\t\tEMP Columbia BusSchool$/\tColumbia University\tMBA\t/;
  s/\t\t\tMBA Columbia$/\tColumbia University\tMBA\t/;
  s/\t\t\tMS Columbia$/\tColumbia University\tMSc\t/;
  s/\t\t\tMSEE Columbia Univ$/\tColumbia University\tM\tMSEE/;
  s/\t\t\tMBA Univ Columbia$/\tColumbia University\tMBA\t/;
  s/\t\t\tMFSE Columbia Univ$/\tColumbia University\tM\tMFSE/;
  s/\t\t\tMSc Univ Columbia$/\tColumbia University\tMSc\t/;
  s/\t\t\tPhD Columbia$/\tColumbia University\tPhD\t/;
  s/\t\t\tMS Univ British Columbia$/\tUBC\tMSc\t/;
  s/\t\t\tMSc Univ British Columbia$/\tUBC\tMSc\t/;
  s/\t\t\tMBA Chicago$/\tUniversity of Chicago\tMBA\t/;
  s/\t\t\tMsChicago$/\tUniversity of Chicago\tMSc\t/;
  s/\t\t\tMSc Univ Chicago$/\tUniversity of Chicago\tMSc\t/;
  s/\t\t\tPhD EconomChicago$/\tUniversity of Chicago\tPhD\tÉconomie/;
  s/\t\t\tPhD Univ Chicago$/\tUniversity of Chicago\tPhD\t/;
  s/\t\t\tMS Imperial College$/\tImperial College\tMSc\t/;
  s/\t\t\tMS Imperial College Londres$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc Imperial College$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc Imperial Collège$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc Imperial Collège GB$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc Imperial College of London$/\tImperial College\tMSc\t/;
  s/\t\t\tM Sc Imperial College$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc in Advanced Mechanical Engin \, Imperial College Londres$/\tImperial College\tMSc\tAdvanced Mechanical Engineering/;
  s/\t\t\tMSc Impreial College of London$/\tImperial College\tMSc\t/;
  s/\t\t\tMSc Impérial Collège$/\tImperial College\tMSc\t/;
  s/\t\t\tPhD Imperial College$/\tImperial College\tPhD\t/;
  s/\t\t\tMS London School of Economics$/\tLSE\tMSc\t/;
  s/\t\t\tMScLondon School of Economics$/\tLSE\tMSc\t/;
  s/\t\t\tMSc London School of Economics & Political Science$/\tLSE\tMSc\t/;
  s/\t\t\tMSc London School of Economics$/\tLSE\tMSc\t/;
  s/\t\t\tMSc London School Economics$/\tLSE\tMSc\t/;
  s/\t\t\tLondon School of Economics$/\tLSE\tM\t/;
  s/\t\t\tM Sc London School of Economics$/\tLSE\tMSc\t/;
  s/\t\t\tMScLondon School of Eco$/\tLSE\tMSc\t/;
  s/\t\t\tMSc of The London School of Economics and Political Science$/\tLSE\tMSc\t/;
  s/\t\t\tMSc The London School of Economics & Political Science$/\tLSE\tMSc\t/;
  s/\t\t\tMS Lonson School of Economics$/\tLSE\tMSc\t/;
  s/\t\t\tMS LSE Londres$/\tLSE\tMSc\t/;
  s/\t\t\tMSc Finance LSE$/\tLSE\tMSc\tFinance/;
  s/\t\t\tLSE$/\tLSE\tM\t/;
  s/\t\t\tMS LSE$/\tLSE\tMSc\t/;
  s/\t\t\tPhD London School Econ& Polit Sc$/\tLSE\tPhD\t/;
  s/\t\t\tPhD London School of Econ$/\tLSE\tPhD\t/;
  s/\t\t\tMSc Univ College of London$/\tUCL\tMSc\t/;
  s/\t\t\tUniversity CollLondres$/\tUCL\tM\t/;
  s/\t\t\tMS Signal et Communications Londres$/\tUCL\tMSc\tSignal et Communications/;
  s/\t\t\tPhD London Royaume uni$/\tUCL\tPhD\t/;
  s/\t\t\tMS Philoet Eco Londres$/\tUCL\tMSc\tPhilosophie et économie/;
  s/\t\t\tMS Economie de l'environ et ressources naturelles UCL Londres$/\tUCL\tMSc\tÉconomie de l'environnement et des ressources naturelles/;
  s/\t\t\tMSc in Finance and Economics Londres$/\tUCL\tMSc\tFinance and Economics/;
  s/\t\t\tPhD London$/\tUCL\tPhD\t/;
  s/\t\t\tMBA London Business School$/\tLondon Business School\tMBA\t/;
  s/\t\t\tMS in Finance London Business School$/\tLondon Business School\tMSc\tFinances/;
  s/\t\t\tLondon Business School$/\tLondon Business School\tM\t/;
  s/\t\t\tRoyal College of Art Londres$/\tRCA\tMA\t/;
  s/\t\t\tMS CIT$/\tCalTech\tMSc\t/;
  s/\t\t\tMS Caltech$/\tCalTech\tMSc\t/;
  s/\t\t\tMS CalTech$/\tCalTech\tMSc\t/;
  s/\t\t\tME CalTech$/\tCalTech\tME\t/;
  s/\t\t\tPhD Caltech$/\tCalTech\tPhD\t/;
  s/\t\t\tPhD CalTech$/\tCalTech\tPhD\t/;
  s/\t\t\tMSc Univ Northwestern$/\tNU\tMSc\t/;
  s/\t\t\tPhD Northwestern University$/\tNU\tPhD\t/;
  s/\t\t\tMScNY$/\tNYU\tMSc\t/;
  s/\t\t\tMS Schenectady NY$/\tNYU\tMSc\t/;
  s/\t\t\tMS Univ New York$/\tNYU\tMSc\t/;
  s/\t\t\tMS New York University$/\tNYU\tMSc\t/;
  s/\t\t\tMBA New York University$/\tNYU\tMBA\t/;
  s/\t\t\tMSc Univ New York$/\tNYU\tMSc\t/;
  s/\t\t\tMS Univ New-York$/\tNYU\tMSc\t/;
  s/\t\t\tMS New York$/\tNYU\tMSc\t/;
  s/\t\t\tME Univ New York$/\tNYU\tME\t/;
  s/\t\t\tMS New York$/\tNYU\tMSc\t/;
  s/\t\t\tMSc New York Univ$/\tNYU\tMSc\t/;
  s/\t\t\tMS New york$/\tNYU\tMSc\t/;
  s/\t\t\tPhD Univ New York$/\tNYU\tPhD\t/;
  s/\t\t\tPhD Watson School of Biological Sciences$/\tWSBS\tPhD\tBiologie/;
  s/\t\t\tMS McGill University$/\tMcGill\tMSc\t/;
  s/\t\t\tMaster of Management McGill University$/\tMcGill\tMM\t/;
  s/\t\t\tMS Univ McGill$/\tMcGill\tMSc\t/;
  s/\t\t\tMSc Mc Gill Univ$/\tMcGill\tMSc\t/;
  s/\t\t\tMSc Univ McGill$/\tMcGill\tMSc\t/;
  s/\t\t\tMSc Mc Gill University$/\tMcGill\tMSc\t/;
  s/\t\t\tMS McGill$/\tMcGill\tMSc\t/;
  s/\t\t\tPhD Univ McGill$/\tMcGill\tPhD\t/;
  s/\t\t\tUniversity of Illinois$/\tUniversity of Illinois\tM\t/;
  s/\t\t\tMS Univ Illinois$/\tUniversity of Illinois\tMSc\t/;
  s/\t\t\tMSc Univ Illinois$/\tUniversity of Illinois\tMSc\t/;
  s/\t\t\tPhD Univ Illinois$/\tUniversity of Illinois\tPhD\t/;
  s/\t\t\tPh\ D Univ Iowa$/\tUniversity of Iowa\tPhD\t/;
  s/\t\t\tMA ElectEngineerPrinceton$/\tPrinceton\tMA\tElectrical Engineering/;
  s/\t\t\tMSc Princeton$/\tPrinceton\tMSc\t/;
  s/\t\t\tMS Univ Princeton$/\tPrinceton\tMSc\t/;
  s/\t\t\tMS Princeton$/\tPrinceton\tMSc\t/;
  s/\t\t\tMS Univ Princeton$/\tPrinceton\tMSc\t/;
  s/\t\t\tMSc Univ Princeton$/\tPrinceton\tMSc\t/;
  s/\t\t\tMS in Finance Princeton$/\tPrinceton\tMSc\tFinance/;
  s/\t\t\tPhD Princeton$/\tPrinceton\tPhD\t/;
  s/\t\t\tPhD Univ Princeton$/\tPrinceton\tPhD\t/;
  s/\t\t\tMSc Design UNSW$/\tUNSW\tMSc\tDesign/;
  s/\t\t\tMS Univ New South Wales$/\tUNSW\tMSc\t/;
  s/\t\t\tMSc Univ of New South Wales$/\tUNSW\tMSc\t/;
  s/\t\t\tME Univ New South Wales Sydney$/\tUNSW\tME\t/;
  s/\t\t\tMES Sydney$/\tUNSW\tM\tMES/;
  s/\t\t\tME Univ New South Wales Sydney Austr$/\tUNSW\tME\t/;
  s/\t\t\tMaster of Env Engin Science UNSW Sydney$/\tUNSW\tM\t/;
  s/\t\t\tME Univ New South Wales Sydney$/\tUNSW\tME\t/;
  s/\t\t\tMS Univ New South Wales Sydney Australie$/\tUNSW\tMSc\t/;
  s/\t\t\tMS University of Sydney$/\tUNSW\tMSc\t/;
  s/\t\t\tPhD Univ New South Wales Sydney Australia$/\tUNSW\tPhD\t/;
  s/\t\t\tMS Univ Johns Hopkins$/\tJHU\tMSc\t/;
  s/\t\t\tMSc John Hopkins Univ$/\tJHU\tMSc\t/;
  s/\t\t\tPhD Univ Johns Hopkins$/\tJHU\tPhD\t/;
  s/\t\t\tMS Univ du Québec à Montréal$/\tUQÀM\tMSc\t/;
  s/\t\t\tMS Québec$/\tUQÀM\tMSc\t/;
  s/\t\t\tPhD Univ Montréal$/\tUQÀM\tPhD\t/;
  s/\t\t\tMS EcPolytMontreal$/\tEPM\tMSc\t/;
  s/\t\t\tMS Montréal$/\tEPM\tMSc\t/;
  s/\t\t\tEP Montréal$/\tEPM\tM\t/;
  s/\t\t\tMS Montréal Biotechnology$/\tEPM\tMSc\tBiotechnologie/;
  s/\t\t\tEP Montréal MS$/\tEPM\tMSc\t/;
  s/\t\t\tMSc EP Montréal$/\tEPM\tMSc\t/;
  s/\t\t\tMS EP Montréal$/\tEPM\tMSc\t/;
  s/\t\t\tIng EP Montréal$/\tEPM\tIng.\t/;
  s/\t\t\tIng Ecole polytechnique de Montréal$/\tEPM\tIng.\t/;
  s/\t\t\tEP Montréal Ing$/\tEPM\tIng.\t/;
  s/\t\t\tIng Univ RWTH-Aachen$/\tRWTH\tIng.\t/;
  s/\t\t\tIng Univ RWTH-AAchen$/\tRWTH\tIng.\t/;
  s/\t\t\tRWTH Aachen$/\tRWTH\tM\t/;
  s/\t\t\tMS Univ RWTH-Aachen$/\tRWTH\tMSc\t/;
  s/\t\t\tUniv RWTH Aachen$/\tRWTH\tM\t/;
  s/\t\t\tMS Univ Th Aachen$/\tRWTH\tMSc\t/;
  s/\t\t\tME Univ TH Aachen$/\tRWTH\tME\t/;
  s/\t\t\tMSc Univ TH Aachen$/\tRWTH\tMSc\t/;
  s/\t\t\tMS Univ Catalunya$/\tUOC\tMSc\t/;
  s/\t\t\tME Univ Catalunya$/\tUOC\tME\t/;
  s/\t\t\tPhD Univ Catalunya$/\tUOC\tPhD\t/;
  s/\t\t\tUCSD$/\tUCSD\tM\t/;
  s/\t\t\tMSc UCSD Océanographie physique$/\tUCSD\tMSc\tOcéanographie physique/;
  s/\t\t\tMS Univ of California San Diego$/\tUCSD\tMSc\t/;
  s/\t\t\tMSc UC San Diego$/\tUCSD\tMSc\t/;
  s/\t\t\tMS Univ San Diego$/\tUCSD\tMSc\t/;
  s/\t\t\tMS UC San Diego$/\tUCSD\tMSc\t/;
  s/\t\t\tPhD Univ San Diego$/\tUCSD\tPhD\t/;
  s/\t\t\tPhD San Diego$/\tUCSD\tPhD\t/;
  s/\t\t\tMBA Queen's Univ Canada$/\tQueen's\tMBA\t/;
  s/\t\t\tPhD UBC Canada$/\tUBC\tPhD\t/;
  s/\t\t\tMSc UnivOxford$/\tOxford\tMSc\t/;
  s/\t\t\tMS Univ Oxford$/\tOxford\tMSc\t/;
  s/\t\t\tMS Oxford$/\tOxford\tMSc\t/;
  s/\t\t\tMSc Univ Oxford$/\tOxford\tMSc\t/;
  s/\t\t\tMSc Oxford$/\tOxford\tMSc\t/;
  s/\t\t\tME Univ Oxford$/\tOxford\tME\t/;
  s/\t\t\tMSc Univ of Oxford$/\tOxford\tMSc\t/;
  s/\t\t\tPhD Univ Oxford$/\tOxford\tPhD\t/;
  s/\t\t\tPhD Boulder$/\tCU\tPhD\t/;
  s/\t\t\tMS Singapour$/\tNUS\tMSc\t/;
  s/\t\t\tMSc Nat Univ of Singapore$/\tNUS\tMSc\t/;
  s/\t\t\tMSc National Univ of Singapore$/\tNUS\tMSc\t/;
  s/\t\t\tMSc National University of Singapour$/\tNUS\tMSc\t/;
  s/\t\t\tPhD Univ Singapour$/\tNUS\tPhD\t/;
  s/\t\t\tMBA Carnegie Mellon$/\tCMU\tMBA\t/;
  s/\t\t\tMS Carnegie Mellon$/\tCMU\tMSc\t/;
  s/\t\t\tMS ComputCarnégie Mellon Univ$/\tCMU\tMSc\tInformatique/;
  s/\t\t\tPhD Carnegie Mellon$/\tCMU\tPhD\t/;
  s/\t\t\tMSc Univ NTNU$/\tNTNU\tMSc\t/;
  s/\t\t\tPhD NTNU$/\tNTNU\tPhD\t/;
  s/\t\t\tMS Georgia Tech$/\tGeorgia Tech\tMSc\t/;
  s/\t\t\tMS Univ Georgia$/\tGeorgia Tech\tMSc\t/;
  s/\t\t\tMSc Georgia Tech$/\tGeorgia Tech\tMSc\t/;
  s/\t\t\tMSc GeorgiaTech$/\tGeorgia Tech\tMSc\t/;
  s/\t\t\tPhD GeorgiaTech$/\tGeorgia Tech\tPhD\t/;
  s/\t\t\tPhD Univ Surrey$/\tUniversity of Surrey\tPhD\t/;
  s/\t\t\tMS Kyoto$/\tKyoto University\tMSc\t/;
  s/\t\t\tPhD Univ Kyoto$/\tKyoto University\tPhD\t/;
  s/\t\t\tMS Tokyo$/\tTodai\tMSc\t/;
  s/\t\t\tMSc Univ de Tokyo$/\tTodai\tMSc\t/;
  s/\t\t\tME Univ Tokyo$/\tTodai\tME\t/;
  s/\t\t\tMSc Univ of Tokyo$/\tTodai\tMSc\t/;
  s/\t\t\tPhD UnivTokyo$/\tTodai\tPhD\t/;
  s/\t\t\tPhD Univ Tokyo$/\tTodai\tPhD\t/;
  s/\t\t\tPhD Tokyo Institute of Technology$/\tTokyo Tech\tPhD\t/;
  s/\t\t\tIngDiplUniversité Stuttgart$/\tUniversität Stuttgart\tIng.\t/;
  s/\t\t\tIng Stuttgart$/\tUniversität Stuttgart\tIng.\t/;
  s/\t\t\tIng diplomé Fac d'Aéronautique de Stuttgart$/\tUniversität Stuttgart\tIng.\tAéronautique/;
  s/\t\t\tME Univ Stuttgart$/\tUniversität Stuttgart\tME\t/;
  s/\t\t\tMSc Univ Stuttgart$/\tUniversität Stuttgart\tMSc\t/;
  s/\t\t\tMS Univ Stuttgart$/\tUniversität Stuttgart\tMSc\t/;
  s/\t\t\tDiplome de la Empire Test Pilot's School$/\tETPS\tDipl.\t/;
  s/\t\t\tIngde Caminos de Madrid$/\tUPM\tIng.\t/;
  s/\t\t\tIngeniero Industrial UPM Madrid$/\tUPM\tIng.\t/;
  s/\t\t\tEscuela Sup de Ing de Caminos Canales y Puertos$/\tUPM\tIng.\t/;
  s/\t\t\tMS Univ Madrid$/\tUPM\tMSc\t/;
  s/\t\t\tUniv Madrid$/\tUPM\tM\t/;
  s/\t\t\tME Univ Madrid$/\tUPM\tME\t/;
  s/\t\t\tME UnivMadrid$/\tUPM\tME\t/;
  s/\t\t\tMS Madrid$/\tUPM\tMSc\t/;
  s/\t\t\tETSII Madrid$/\tUPM\tM\tETSSI/;
  s/\t\t\tMSc Madrid$/\tUPM\tMSc\t/;
  s/\t\t\tME : Univ Madrid$/\tUPM\tME\t/;
  s/\t\t\tMSc Univ Madrid$/\tUPM\tMSc\t/;
  s/\t\t\tMSc Univ Politècnica de Madrid$/\tUPM\tMSc\t/;
  s/\t\t\tIng Univ Polytech Bucarest$/\tPolitehnica din Bucureşti\tIng.\t/;
  s/\t\t\tIng Univ Catolica de Chile$/\tPUC\tIng.\t/;
  s/\t\t\tMS NDame Indiana$/\tNotre Dame\tMSc\t/;
  s/\t\t\tMS Pasadena$/\tPLNU\tMSc\t/;
  s/\t\t\tMBA Kellogg School of Management$/\tKellogg\tMBA\t/;
  s/\t\t\tMBA Kellogg school of Management$/\tKellogg\tMBA\t/;
  s/\t\t\tInvestment Banking Program-Kellog School of Management$/\tKellogg\tMBA\tInvestment Banking Program/;
  s/\t\t\tMS Houston$/\tUH\tMSc\t/;
  s/\t\t\tEngineer Kentucky$/\tUK\tIng.\tEngineer/;
  s/\t\t\tEP Gdansk Pologne$/\tUniwersytet Gdański\tM\t/;
  s/\t\t\tMS StatTexas A&M Univ$/\tTAMU\tMSc\t/;
  s/\t\t\tMS Texas A&M University$/\tTAMU\tMSc\t/;
  s/\t\t\tME Univ Texas$/\tTAMU\tME\t/;
  s/\t\t\tMSc Univ Texas$/\tTAMU\tMSc\t/;
  s/\t\t\tMS Univ Texas A&M$/\tTAMU\tMSc\t/;
  s/\t\t\tMSc Texas A&M Univ$/\tTAMU\tMSc\t/;
  s/\t\t\tMS Caroline du Nord Chapel Hill$/\tCarolina\tMSc\t/;
  s/\t\t\tMS Davis$/\tUC Davis\tMSc\t/;
  s/\t\t\tMS UC Davis$/\tUC Davis\tMSc\t/;
  s/\t\t\tMS Univ TU München$/\tTU München\tMSc\t/;
  s/\t\t\tMS Univ TU Munich$/\tTU München\tMSc\t/;
  s/\t\t\tMS München$/\tTU München\tMSc\t/;
  s/\t\t\tMSc Univ TU Munich$/\tTU München\tMSc\t/;
  s/\t\t\tME Univ TU Munich$/\tTU München\tME\t/;
  s/\t\t\tMS Ottawa$/\tOU\tMSc\t/;
  s/\t\t\tMPhilSheffield$/\tUniversity of Sheffield\tMPhil\t/;
  s/\t\t\tMS Urbana$/\tUrbana University\tMSc\t/;
  s/\t\t\tMS Maryland$/\tUMCP\tMSc\t/;
  s/\t\t\tKTH Stockholm Master Mech Eng$/\tKTH\tM\tMécanique/;
  s/\t\t\tMS Univ KTH$/\tKTH\tMSc\t/;
  s/\t\t\tMSc Univ KTH$/\tKTH\tMSc\t/;
  s/\t\t\tMSc KTH$/\tKTH\tMSc\t/;
  s/\t\t\tMSc Eng Birmingham$/\tUniversity of Birmingham\tMSc\t/;
  s/\t\t\tMaster ChemEngAMHERST MA$/\tAmherst College\tMA\tChimie/;
  s/\t\t\tMS Univ Washington$/\tUniversity of Washington\tMSc\t/;
  s/\t\t\tICAF Washington$/\tNDU\tM\tICAF/;
  s/\t\t\tMSc Washington DC National Defense Univ$/\tNDU\tMSc\t/;
  s/\t\t\tMBA Collège EuropBruges$/\tCollege of Europe\tMBA\tBruges/;
  s/\t\t\tCollège d'Europe Natolin Varsovie$/\tCollege of Europe\tMBA\tNatolin Varsovie/;
  s/\t\t\tCFA$/\tCFA Institute\tMBA\t/;
  s/\t\t\tChartered Financial Analyst$/\tCFA Institute\tMBA\tFinancial Analyst/;
  s/\t\t\tChartered Institute of Management Accountant$/\tCIMA\tMBA\t/;
  s/\t\t\tNaval Postgraduate School$/\tNPS\tDipl.\t/;
  s/\t\t\tMBA Rotterdam School of Management$/\tRSM\tMBA\t/;
  s/\t\t\tME Univ Torino$/\tUNITO\tME\t/;
  s/\t\t\tMSc Petroleum Engineering \- TU Delft$/\tTU Delft\tMSc\tPetroleum Engineering/;
  s/\t\t\tMS Univ TU Delft$/\tTU Delft\tMSc\t/;
  s/\t\t\tMSc Univ TU Delft$/\tTU Delft\tMSc\t/;
  s/\t\t\tMSc Karlsruhe$/\tUniversität Karlsruhe\t\t/;
  s/\t\t\tMS Univ Karlsruhe$/\tUniversität Karlsruhe\t\t/;
  s/\t\t\tMS Univ Moscow$/\tMGU\tMSc\t/;
  s/\t\t\tUniv Moscow : ME$/\tMGU\tME\t/;
  s/\t\t\tMBA Univ Californie Irvine$/\tUCI\tMBA\t/;
  s/\t\t\tMBA Henley$/\tHenley\tMBA\t/;
  s/\t\t\tMBA Henley Management College$/\tHenley\tMBA\t/;
  s/\t\t\tMBA Univ of Dallas$/\tUniversity of Dallas\tMBA\t/;
  s/\t\t\tMSc Univ Milano$/\tUNIMI\tMSc\t/;
  s/\t\t\tMS Politecnico di Milano$/\tPolitecnico di Milano\tMSc\t/;
  s/\t\t\tMSc Politecnico di Milano$/\tPolitecnico di Milano\tMSc\t/;
  s/\t\t\tME Univ TU Berlin$/\tTU Berlin\tME\t/;
  s/\t\t\tMSc Univ Bocconi$/\tUniversità Bocconi\tMSc\t/;
  s/\t\t\tMSc Univ Bocconi$/\tUniversità Bocconi\tMSc\t/;
  s/\t\t\tMSc Univ Pompeu Fabra$/\tUPF\tMSc\t/;
  s/\t\t\tMS Univ Pompeu Fabra$/\tUPF\tMSc\t/;
  s/\t\t\tMSc Pompeu Fabra$/\tUPF\tMSc\t/;
  s/\t\t\tMSc Univ Southampton$/\tUniversity of Southampton\tMSc\t/;
  s/\t\t\tMS Southampton$/\tUniversity of Southampton\tMSc\t/;
  s/\t\t\tMSc Univ Tsinghua$/\tTHU\tMSc\t/;
  s/\t\t\tMS Univ Tsinghua$/\tTHU\tMSc\t/;
  s/\t\t\tMS Univ Chalmers$/\tChalmers\tMSc\t/;
  s/\t\t\tOIV Wine Industry Management$/\tOIV\tMSc\t/;
  s/\t\t\tMS Indian Institutes of Technology$/\tIITs\tMSc\t/;
  s/\t\t\tMSc Univ Technion$/\tTechnion\tMSc\t/;
  s/\t\t\tMSc Kungliga Tekniska Högskolan$/\tKTH\tMSc\t/;
  s/\t\t\tMS Univ Stockholm$/\tStockholms Universitet\tMSc\t/;

  # Diploma missing.
  s/\t\t\tUniv Syracuse USA$/\tSU\t\t/;
  s/\t\t\tHarvard$/\tHarvard\t\t/;
  s/\t\t\tTexas A&M University$/\tTAMU\t\t/;
  s/\t\t\tMIT$/\tMIT\t\t/;
  s/\t\t\tUniv TU München$/\tTU München\t\t/;
  s/\t\t\tUniv Paris XI$/\tParis-Sud\t\t/;
  s/\t\t\tIESTO$/\tENSAM\t\t/;
  s/\t\t\tCNAM$/\tENSAM\t\t/;
  s/\t\t\tISUP$/\tUPMC\t\tISUP/;
  s/\t\t\tBauman Univ Moscou$/\tBauman MSTU\t\t/;
  s/\t\t\tUniv Leiden$/\tUniversiteit Leiden\t\t/;
  s/\t\t\tBusiness School Dartmouth$/\tDartmouth College\t\t/;
  s/\t\t\tBocconi University Milan$/\tUniversità Bocconi\t\t/;

  # University missing.
  s/\t\t\tBTS Technique agricole$/\t\tBTS\tTechnique agricole/;
  s/\t\t\tDEUG Russe$/\t\tDEUG\tRusse/;
  s/\t\t\tDEUG Droit$/\t\tDEUG\tDroit/;
  s/\t\t\tDEUG$/\t\tDEUG\t/;
  s/\t\t\tLicen Droit$/\t\tLic.\tDroit/;
  s/\t\t\tLicencié en droit$/\t\tLic.\tDroit/;
  s/\t\t\tLicès Lettres$/\t\tLic.\tLettres/;
  s/\t\t\tLicès Sc$/\t\tLic.\tSciences/;
  s/\t\t\tLicen Théologie$/\t\tLic.\tThéologie/;
  s/\t\t\tLicès ScEcon$/\t\tLic.\tÉconomie/;
  s/\t\t\tLicen Maths$/\t\tLic.\tMathématiques/;
  s/\t\t\tLic Sc Eco$/\t\tLic.\tÉconomie/;
  s/\t\t\tLicEcoAppliquée$/\t\tLic.\tÉconomie appliquée/;
  s/\t\t\tLicArabe Littéral$/\t\tLic.\tArabe Littéral/;
  s/\t\t\tLic en psychologie$/\t\tLic.\tPsychologie/;
  s/\t\t\tLicen Théologie cath$/\t\tLic.\tThéologie catholique/;
  s/\t\t\tLicès ScEcon Finance$/\t\tLic.\tÉconomie Finance/;
  s/\t\t\tLic d'Histoire\, d'Anglais\, de Lettres classiques & modernes$/\t\tLic.\tHistoire Anglais Lettres classiques et modernes/;
  s/\t\t\tLicen philosophie et théologie$/\t\tLic.\tPhilosophie Théologie/;
  s/\t\t\tLic Science$/\t\tLic.\tSciences/;
  s/\t\t\tLic canonique en théologie$/\t\tLic.\tThéologie/;
  s/\t\t\tLicence d'Histde l'Art$/\t\tLic.\tHistoire de l'art/;
  s/\t\t\tLicence Philosophie$/\t\tLic.\tPhilosophie/;
  s/\t\t\tMaîtrise ScEcon$/\t\tMaîtr.\tÉconomie/;
  s/\t\t\tMa(î|i)trise en (.*)$/\t\tMaîtr.\t\2/;
  s/\t\t\tMa(î|i)trise ès (.*)$/\t\tMaîtr.\t\2/;
  s/\t\t\tMa(î|i)trise de (.*)$/\t\tMaîtr.\t\2/;
  s/\t\t\tMaître ès Lettres Anglais$/\t\tMaîtr.\tLettres (Anglais)/;
  s/\t\t\tMaîtrise Théologie Catholique$/\t\tMaîtr.\tThéologie Catholique/;
  s/\t\t\tMaîtrise d'Histoire$/\t\tMaîtr.\tHistoire/;
  s/\t\t\tMaitrise Biochimie$/\t\tMaîtr.\tBiologie/;
  s/\t\t\tMaitrise Génie Electrique$/\t\tMaîtr.\tGénie Electrique/;
  s/\t\t\tDES EconPo$/\t\tDESS\tÉconomie/;
  s/\t\t\tDES Sc$/\t\tDESS\tSciences/;
  s/\t\t\tDESS Droit$/\t\tDESS\tDroit/;
  s/\t\t\tDESS Droit des affaires$/\t\tDESS\tDroit des affaires/;
  s/\t\t\tDESS Affaires Internationales$/\t\tDESS\tAffaires Internationales/;
  s/\t\t\tDESS Finance$/\t\tDESS\tFinance/;
  s/\t\t\tDESS Gestion$/\t\tDESS\tGestion/;
  s/\t\t\tDESS ScEconom$/\t\tDESS\tÉconomie/;
  s/\t\t\tDESS Gestion des Ress Naturelles Renouvelables$/\t\tDESS\tGestion des ressources naturelles renouvelables/;
  s/\t\t\tDESS dével culturel et dir de projet$/\t\tDESS\tDéveloppement culturel et direction de projets/;
  s/\t\t\tDESS Management Paris$/\t\tDESS\tManagement/;
  s/\t\t\tDESS Défense Stratégies & Dynamiques ind$/\t\tDESS\tDéfense Stratégies & Dynamiques indépendantes/;
  s/\t\t\tDEA$/\t\tDEA\t/;
  s/\t\t\tDEA Univ$/\t\tDEA\t/;
  s/\t\t\tDEA d'Histoire$/\t\tDEA\tHistoire/;
  s/\t\t\tDEA Univ Paris Chimie I et II Chimie Physique$/\t\tDEA\tChimie Physique/;
  s/\t\t\tDEA ScEcon$/\t\tDEA\tÉconomie/;
  s/\t\t\tDEA Phys$/\t\tDEA\tPhysique/;
  s/\t\t\tDEA Finance$/\t\tDEA\tFinance/;
  s/\t\t\tDEA d'Astrophysique$/\t\tDEA\tAstrophysique/;
  s/\t\t\tDEA Electron$/\t\tDEA\tÉlectronique/;
  s/\t\t\tDEA Théorie de l'Information$/\t\tDEA\tThéorie de l'Information/;
  s/\t\t\tDEA PhysNucléaire$/\t\tDEA\tPhysique nucléaire/;
  s/\t\t\tDEA Méca FluidThéor$/\t\tDEA\tMécanique des fuildes théorique/;
  s/\t\t\tDEA Maths Applà l'Economie$/\t\tDEA\tMathématiques appliquées à l'économie/;
  s/\t\t\tDEA PhysRéact$/\t\tDEA\tPhysique/;
  s/\t\t\tDEA Intelligence Artificielle$/\t\tDEA\tIntelligence Artificielle/;
  s/\t\t\tDEA d'Automatique$/\t\tDEA\tAutomatique/;
  s/\t\t\tDEA Analyse Numérique$/\t\tDEA\tAnalyse Numérique/;
  s/\t\t\tDEA Econométrie$/\t\tDEA\tEconométrie/;
  s/\t\t\tDEA EcoRechDévelop$/\t\tDEA\tÉconomie Rechercche et Développement/;
  s/\t\t\tDEA Océanographie$/\t\tDEA\tOcéanographie/;
  s/\t\t\tDEA Informatique$/\t\tDEA\tInformatique/;
  s/\t\t\tDEA Physdes Solides$/\t\tDEA\tPhysique des solides/;
  s/\t\t\tDEA Droit$/\t\tDEA\tDroit/;
  s/\t\t\tDEA Economie$/\t\tDEA\tÉconomie/;
  s/\t\t\tDEA d'Histoire Droit$/\t\tDEA\tHistoire Droit/;
  s/\t\t\tDEA Gestion$/\t\tDEA\tGestion/;
  s/\t\t\tDEA Analyse donnée$/\t\tDEA\tAnalyse de données/;
  s/\t\t\tDEA Math$/\t\tDEA\tMathématiques/;
  s/\t\t\tDEA PhysThéor$/\t\tDEA\tPhysique théorique/;
  s/\t\t\tDEA Ecologie$/\t\tDEA\tÉcologie/;
  s/\t\t\tDEA PolitEco& Soc$/\t\tDEA\tPolitique économique et sociale/;
  s/\t\t\tDEA Sc du Bois$/\t\tDEA\tScience du bois/;
  s/\t\t\tDEA Syst énergétiques$/\t\tDEA\tSystèmes énergétiques/;
  s/\t\t\tDEA Economie Développement$/\t\tDEA\tÉconomie Développement/;
  s/\t\t\tDEA Sciences et Techniques de l'Environnement Créteil$/\t\tDEA\tSciences et Techniques de l'Environnement/;
  s/\t\t\tDEA Sc & Techniques de l'Environnement$/\t\tDEA\tSciences et Techniques de l'Environnement/;
  s/\t\t\tDEA Scde l'Eau$/\t\tDEA\tScience de l'eau/;
  s/\t\t\tDEA Analyse Industr$/\t\tDEA\tAnalyse industrielle/;
  s/\t\t\tDEA Optique$/\t\tDEA\tOptique/;
  s/\t\t\tDEA Mécanique$/\t\tDEA\tMécanique/;
  s/\t\t\tDEA de Génie Electrique$/\t\tDEA\tGénie électrique/;
  s/\t\t\tDEA Microbiologie$/\t\tDEA\tMicrobiologie/;
  s/\t\t\tDEA Energétique$/\t\tDEA\tÉnergétique/;
  s/\t\t\tDEA Acoustique$/\t\tDEA\tAcoustique/;
  s/\t\t\tDEA RechOpérationnelle$/\t\tDEA\tRecherche Opérationnelle/;
  s/\t\t\tDEA Sc des Matériaux$/\t\tDEA\tScience des Matériaux/;
  s/\t\t\tDEA Eco Finance Internationale$/\t\tDEA\tÉconomie Finance Internationale/;
  s/\t\t\tDEA Procédés$/\t\tDEA\tProcédés/;
  s/\t\t\tDEA Cryptographe\/Algorighmie$/\t\tDEA\tCryptographe Algorithmique/;
  s/\t\t\tDEA Microéconomie$/\t\tDEA\tMicroéconomie/;
  s/\t\t\tDEA Probabilités$/\t\tDEA\tProbabilités/;
  s/\t\t\tDEA ScCognitives$/\t\tDEA\tScience cognitives/;
  s/\t\t\tDEA biomécanique$/\t\tDEA\tBiomécanique/;
  s/\t\t\tDEA Chimie Organique$/\t\tDEA\tChimie Organique/;
  s/\t\t\tDEA Acoustique musicale$/\t\tDEA\tAcoustique musicale/;
  s/\t\t\tDEA Milieux Coralliens$/\t\tDEA\tMilieux Coralliens/;
  s/\t\t\tDEA Urbanisme$/\t\tDEA\tUrbanisme/;
  s/\t\t\tDEA Analyse & Polit Eco$/\t\tDEA\tAnalyse et Politique Économique/;
  s/\t\t\tDEA Immunologie$/\t\tDEA\tImmunologie/;
  s/\t\t\tDEA MathAppliquées$/\t\tDEA\tMathématiques appliquées/;
  s/\t\t\tDEA Génie des Procédés$/\t\tDEA\tGénie des Procédés/;
  s/\t\t\tDEA Informatique Math& Appl$/\t\tDEA\tInformatique Mathématiques appliquées/;
  s/\t\t\tDEA Sc Info Géographique$/\t\tDEA\tInformatique géographique/;
  s/\t\t\tDEA de Biologie$/\t\tDEA\tBiologie/;
  s/\t\t\tDEA Maths Financières$/\t\tDEA\tMathématiques Financières/;
  s/\t\t\tDEA Analyse & Polit Eco$/\t\tDEA\tAnalyse et Politique Économique/;
  s/\t\t\tDEA Strat & Marketing$/\t\tDEA\tStratégie et marketting/;
  s/\t\t\tDEA Environnement$/\t\tDEA\tEnvironnement/;
  s/\t\t\tDEA Champs Particules Matières$/\t\tDEA\tChamps Particules Matières/;
  s/\t\t\tDEA Organisation & SystProd$/\t\tDEA\tOrganisation et Système Production/;
  s/\t\t\tDEA Pharmaco& BiolCellulaire$/\t\tDEA\tPharmacologie et Biologie cellulaire/;
  s/\t\t\tDEA Géodynamique & Phys$/\t\tDEA\tGéodynamique et Physique/;
  s/\t\t\tDEA Analyse & Polit Eco$/\t\tDEA\tAnalyse et Politique Économique/;
  s/\t\t\tDEA Toxicologie$/\t\tDEA\tToxicologie/;
  s/\t\t\tDEA Algorithmique$/\t\tDEA\tAlgorithmique/;
  s/\t\t\tDEA Anal ModélSyst Biologi$/\t\tDEA\tAnalyse Modélisation Système Biologique/;
  s/\t\t\tDEA Statistiques$/\t\tDEA\tStatistiques/;
  s/\t\t\tDEA Economie Industrielle$/\t\tDEA\tÉconomie Industrielle/;
  s/\t\t\tDEA ModèlStochastiqStatist$/\t\tDEA\tModélisation Stochastique Statistique/;
  s/\t\t\tDEA EconIndustrielle$/\t\tDEA\tÉconomie Industrielle/;
  s/\t\t\tDEA Processus Stochastiques$/\t\tDEA\tProcessus Stochastiques/;
  s/\t\t\tDEA Hist Philosophie$/\t\tDEA\tHistoire Philosophie/;
  s/\t\t\tDEA Particules & Matière$/\t\tDEA\tParticules et Matière/;
  s/\t\t\tDEA Analyse & Polit Eco$/\t\tDEA\tAnalyse et Politique Économique/;
  s/\t\t\tDEA Solides Structures & Syst Mécaniques$/\t\tDEA\t/;
  s/\t\t\tDEA Chimie Moléculaire$/\t\tDEA\tChimie Moléculaire/;
  s/\t\t\tDEA Hydrologie$/\t\tDEA\tHydrologie/;
  s/\t\t\tDEA Math Appliquées$/\t\tDEA\tMathématiques Appliquées/;
  s/\t\t\tDEA HH GG$/\t\tDEA\t/;
  s/\t\t\tDEA Modélisation Stochastique et Statistique$/\t\tDEA\tModélisation Stochastique et Statistique/;
  s/\t\t\tDEA Pharmacochimie Molexpérimet Métabolisme$/\t\tDEA\tPharmacochimie/;
  s/\t\t\tDEA de Philosophie$/\t\tDEA\tPhilosophie/;
  s/\t\t\tDEA Org et Pilotage des Syst de product$/\t\tDEA\tOrganisation et Pilotage des Systèmes de production/;
  s/\t\t\tDEA Sciences & Techniques de l'environnement$/\t\tDEA\tSciences et Techniques de l'environnement/;
  s/\t\t\tDEA Gestion scientifique$/\t\tDEA\tGestion scientifique/;
  s/\t\t\tDEA Mécanique Fluides$/\t\tDEA\tMécanique Fluides/;
  s/\t\t\tDEA Analyse & Modélisation$/\t\tDEA\tAnalyse et Modélisation/;
  s/\t\t\tDEA Analyse & Politique Eco$/\t\tDEA\tAnalyse et Politique économique/;
  s/\t\t\tDEA Laser & Matière$/\t\tDEA\tLaser et Matière/;
  s/\t\t\tDEA Economie Internationale$/\t\tDEA\tÉconomie Internationale/;
  s/\t\t\tDEA Analyse et Politique Economiques$/\t\tDEA\tAnalyse et Politique économique/;
  s/\t\t\tDEA Economie de l'innovation$/\t\tDEA\tÉconomie de l'innovation/;
  s/\t\t\tDEA Droit public$/\t\tDEA\tDroit public/;
  s/\t\t\tDEA Economie et Finance$/\t\tDEA\tÉconomie et Finance/;
  s/\t\t\tDEA Economie Monétaire & Bancaire$/\t\tDEA\tÉconomie Monétaire et Bancaire/;
  s/\t\t\tDEA Logistique$/\t\tDEA\tLogistique/;
  s/\t\t\tDEA Math Stat$/\t\tDEA\tMathématiques Statistiques/;
  s/\t\t\tDEA Economie de l'Environnement$/\t\tDEA\tÉconomie de l'Environnement/;
  s/\t\t\tDEA Probabilités Finance$/\t\tDEA\tProbabilités Finance/;
  s/\t\t\tDEA Informatique Math et Appli$/\t\tDEA\tInformatique Mathématiques et Applications/;
  s/\t\t\tDEA Robotique$/\t\tDEA\tRobotique/;
  s/\t\t\tDEA Epidémiologie$/\t\tDEA\tEpidémiologie/;
  s/\t\t\tDEA Economie de l'Envir et Ress Nat$/\t\tDEA\tÉconomie de l'Environnement et des Ressources Naturelles/;
  s/\t\t\tDEA Multinational Chimie molécullaire$/\t\tDEA\tMultinational Chimie molécullaire/;
  s/\t\t\tDEA Organisation et Pilotage Syst Product Indust$/\t\tDEA\tOrganisation et Pilotage des Systèmes de Production Industrielle/;
  s/\t\t\tDEA Programmation$/\t\tDEA\tProgrammation/;
  s/\t\t\tDEA Statistique et modèles aléatoires en écon et finances$/\t\tDEA\tStatistique et modèles aléatoires en économie et finances/;
  s/\t\t\tDEA de Marketing$/\t\tDEA\tMarketing/;
  s/\t\t\tDEA Finance Monnaie$/\t\tDEA\tFinance Monnaie/;
  s/\t\t\tDEA Analyse & Politique Economiques$/\t\tDEA\tAnalyse et Politique économique/;
  s/\t\t\tDEA Microélect$/\t\tDEA\tMicroélectronique/;
  s/\t\t\tDEA PhysQuantique$/\t\tDEA\tPhysique quantique/;
  s/\t\t\tDEA Sciences des Sols$/\t\tDEA\tSciences des Sols/;
  s/\t\t\tDEA Probabilités et Applications$/\t\tDEA\tProbabilités et Applications/;
  s/\t\t\tDEA Finance et Monnaie$/\t\tDEA\tFinance et Monnaie/;
  s/\t\t\tDEA d'algorithmique$/\t\tDEA\tAlgorithmique/;
  s/\t\t\tDEA Réseaux$/\t\tDEA\tRéseaux/;
  s/\t\t\tDEA Base Fond de l'Oncogenèse$/\t\tDEA\tBase Fond de l'Oncogenèse/;
  s/\t\t\tDEA Phys Quantique$/\t\tDEA\tPhysique quantique/;
  s/\t\t\tDEA Transports$/\t\tDEA\tTransports/;
  s/\t\t\tDEA Sc matériaux$/\t\tDEA\tSciences des matériaux/;
  s/\t\t\tDEA Economie du Dévelop$/\t\tDEA\tÉconomie du développement/;
  s/\t\t\tDEA Org Production et Entreprise$/\t\tDEA\tOrganisation production et entreprises/;
  s/\t\t\tDEA Physique des Solides$/\t\tDEA\tPhysique des Solides/;
  s/\t\t\tDEA Finance et probabilité$/\t\tDEA\tFinance et probabilité/;
  s/\t\t\tDEA Psychopathologie$/\t\tDEA\tPsychopathologie/;
  s/\t\t\tDEA CPM$/\t\tDEA\tChamps, Particules, Matières/;
  s/\t\t\tDEA Multinational Chimie Moléculaire$/\t\tDEA\tMultinational Chimie Moléculaire/;
  s/\t\t\tDEA Eco Enviro & Ress Humaines$/\t\tDEA\tÉconomie environnementale et ressources humaines/;
  s/\t\t\tDEA Physique Nucléaire$/\t\tDEA\tPhysique Nucléaire/;
  s/\t\t\tDEA Cancérologie$/\t\tDEA\tCancérologie/;
  s/\t\t\tDEA Phys Réacteurs$/\t\tDEA\tPhysique des Réacteurs/;
  s/\t\t\tDEA MVA$/\t\tDEA\tMVA/;
  s/\t\t\tDEA Math Appliquées et Calcul Scient$/\t\tDEA\tMathématiques Appliquées et Calcul Scientifique/;
  s/\t\t\tDEA Economie Ind$/\t\tDEA\tÉconomie/;
  s/\t\t\tDEA Economie des Institutions$/\t\tDEA\tÉconomie des Institutions/;
  s/\t\t\tDEA Interface Physique Biologie$/\t\tDEA\tInterface Physique Biologie/;
  s/\t\t\tDEA Macroéconomie$/\t\tDEA\tMacroéconomie/;
  s/\t\t\tDEA d'hydrologie-hydrogéologie$/\t\tDEA\tHydrologie Hydrogéologie/;
  s/\t\t\tDEA Economie & Finance Internat$/\t\tDEA\tÉconomie et finance internationale/;
  s/\t\t\tDEA de Physique$/\t\tDEA\tPhysique/;
  s/\t\t\tDEA de Sc$/\t\tDEA\tSciences/;
  s/\t\t\tDEA Transport$/\t\tDEA\tTransport/;
  s/\t\t\tDEA Etudes Latines$/\t\tDEA\tÉtudes latines/;
  s/\t\t\tDEA d'Astro, Géophysique & Techn Spatiales$/\t\tDEA\tAstronomie, Géophysique et Techniques Spatiales/;
  s/\t\t\tDEA Biochimic$/\t\tDEA\tBiochimie/;
  s/\t\t\tDEA Informatique Fondamentale$/\t\tDEA\tInformatique Fondamentale/;
  s/\t\t\tDEA Sciences politiques$/\t\tDEA\tSciences politiques/;
  s/\t\t\tDEA Analyse Economique$/\t\tDEA\tAnalyse Économique/;
  s/\t\t\tDEA Math Appliquées aux Sc Eco$/\t\tDEA\tMathématiques Appliquées aux Sciences Économique/;
  s/\t\t\tDEA Télécom Numériques$/\t\tDEA\tTélécom Numériques/;
  s/\t\t\tDEA Mécanique Théorique$/\t\tDEA\tMécanique Théorique/;
  s/\t\t\tDEA Analyse et Politiques$/\t\tDEA\tAnalyse et Politiques/;
  s/\t\t\tDESCF$/\t\tDESCF\t/;
  s/\t\t\tMS ChemEng$/\t\tMSc\tChimie/;
  s/\t\t\tMSc$/\t\tMSc\t/;
  s/\t\t\tMBA$/\t\tMBA\t/;
  s/\t\t\tIng Génie Atomique$/\t\tIng.\tGénie Atomique/;
  s/\t\t\tIngGéophys$/\t\tIng.\tGéophysique/;
  s/\t\t\t.*Médecine.*$/\t\tMD\tMédecine/;
  s/\t\t\tDocten MédecAIHP$/\t\tMD\tMédecine/;
  s/\t\t\tInterne en Chirurgie$/\t\tMD\tChirurgie/;
  s/\t\t\tDocten Théologie$/\t\tPhD\tThéologie/;
  s/\t\t\tDoctès Sc$/\t\tPhD\tSciences/;
  s/\t\t\tDocten Sc$/\t\tPhD\tSciences/;
  s/\t\t\tDoctès ScPhys$/\t\tPhD\tPhysique/;
  s/\t\t\tDocten ScPhys$/\t\tPhD\tPhysique/;
  s/\t\t\tDocten Physique$/\t\tPhD\tPhysique/;
  s/\t\t\tDoctd'Etat ès Sc Phy$/\t\tPhD\tPhysique/;
  s/\t\t\tDoctès ScMath$/\t\tPhD\tMathématiques/;
  s/\t\t\tDocten Math$/\t\tPhD\tMathématiques/;
  s/\t\t\tDocteur en Histoire$/\t\tPhD\tHistoire/;
  s/\t\t\tDoctd'Histoire$/\t\tPhD\tHistoire/;
  s/\t\t\tDocten Droit$/\t\tPhD\tDroit/;
  s/\t\t\tDoctès Lettres$/\t\tPhD\tLettres/;
  s/\t\t\tDoctès Lettres Hist de l'Art$/\t\tPhD\tLettres Hist de l'Art/;
  s/\t\t\tDocten ScEcon$/\t\tPhD\tÉconomie/;
  s/\t\t\tDoctès ScEco$/\t\tPhD\tÉconomie/;
  s/\t\t\tDocten Econ$/\t\tPhD\tÉconomie/;
  s/\t\t\tDoctès ScEcoInternat$/\t\tPhD\tÉconomie/;
  s/\t\t\tDoct3ÈCycle ScEco$/\t\tPhD\tÉconomie/;
  s/\t\t\tDoctEconAppliquée$/\t\tPhD\tÉconomie Appliquée/;
  s/\t\t\tDoctHydrodynamique$/\t\tPhD\tHydrodynamique/;
  s/\t\t\tDoctès ScDipl Européen Graphologie Prof$/\t\tPhD\tGraphologie/;
  s/\t\t\tDoctès ScChim$/\t\tPhD\tChimie/;
  s/\t\t\tDocten Chimie$/\t\tPhD\tChimie/;
  s/\t\t\tDocten ScChim$/\t\tPhD\tChimie/;
  s/\t\t\tDoctès Sc Chimie Organique$/\t\tPhD\tChimie Organique/;
  s/\t\t\tDoctès ScMath Appliquées$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDoctès ScAppl$/\t\tPhD\tSiences/;
  s/\t\t\tDoct3e cycle PhysNucléaire$/\t\tPhD\tPhysique Nucléaire/;
  s/\t\t\tDocten ScPo$/\t\tPhD\tSciences politiques/;
  s/\t\t\tDocten Informatique$/\t\tPhD\tInformatique/;
  s/\t\t\tDoctès ScGestion$/\t\tPhD\tGestion/;
  s/\t\t\tDocten Gestion$/\t\tPhD\tGestion/;
  s/\t\t\tDoct3e Cycle Gestion$/\t\tPhD\tGestion/;
  s/\t\t\tDoctès ScNatur$/\t\tPhD\tBiologie/;
  s/\t\t\tDoct3È Cycle Urbanisme$/\t\tPhD\tUrbanisme/;
  s/\t\t\tDocten Philosophie$/\t\tPhD\tPhilosophie/;
  s/\t\t\tDoct en Scde l'Organisation$/\t\tPhD\tSciences de l'organisation/;
  s/\t\t\tDocten Strat des Org$/\t\tPhD\tStratégie des Organisations/;
  s/\t\t\tDoctManagement Sc$/\t\tPhD\tManagement/;
  s/\t\t\tDoct3e cycle Astrophys$/\t\tPhD\tAstrophysique/;
  s/\t\t\tDocten Physique Chimie des matériaux$/\t\tPhD\tPhysique Chimie des matériaux/;
  s/\t\t\tDoct études extrême orientales$/\t\tPhD\tÉtudes extrême orientales/;
  s/\t\t\tDoctMécdes Fluides$/\t\tPhD\tMécanique des fluides/;
  s/\t\t\tDoctIngBiochimie$/\t\tPhD\tBiochimie/;
  s/\t\t\tDoct en Finance$/\t\tPhD\tFinance/;
  s/\t\t\tDoct Ingenierie & Gestion$/\t\tPhD\tIngénierie Finance/;
  s/\t\t\tDoctEcon& Finance Internat$/\t\tPhD\tÉconomie Finance/;
  s/\t\t\tDoct3ÈCycle MathAppl$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDocten PhysThéor$/\t\tPhD\tPhysique théorique/;
  s/\t\t\tDocten MorpholMath$/\t\tPhD\tMathématiques/;
  s/\t\t\tDocten Physique nucléaire$/\t\tPhD\tPhysique nucléaire/;
  s/\t\t\tDoctIng PhysSolid$/\t\tPhD\tPhysique des solides/;
  s/\t\t\tDoctIngAnalNumér$/\t\tPhD\tAnalyse numérique/;
  s/\t\t\tDoctès Sc Microbiologie$/\t\tPhD\tMicrobiologie/;
  s/\t\t\tDoctIngStatist$/\t\tPhD\tStatistiques/;
  s/\t\t\tDocten Hydrologie$/\t\tPhD\tHydrologie/;
  s/\t\t\tDoctIngPharmacolog$/\t\tPhD\tPharmacologie/;
  s/\t\t\tDoctGénie Procédés$/\t\tPhD\tGénie des procédés/;
  s/\t\t\tDoctGénie des Procédés$/\t\tPhD\tGénie des procédés/;
  s/\t\t\tDoctSc en Géodésie$/\t\tPhD\tGéodésie/;
  s/\t\t\tDoct Univer Ecolo Tropic$/\t\tPhD\tÉcologie tropicale/;
  s/\t\t\tDocten Sc & Génie Matériaux$/\t\tPhD\tGénie Matériaux/;
  s/\t\t\tDocten Biophysique$/\t\tPhD\tBiophysique/;
  s/\t\t\tDoctMathAppliq$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDoctBiologie$/\t\tPhD\tBiologie/;
  s/\t\t\tDoctUnivAutomatique$/\t\tPhD\tAutomatique/;
  s/\t\t\tDoct Bio Moléculaire$/\t\tPhD\tBiologie moléculaire/;
  s/\t\t\tDoct en Aménagement & Urbanisme$/\t\tPhD\tAménagement Urbanisme/;
  s/\t\t\tDoctStat& Santé$/\t\tPhD\tStatistiques Santé/;
  s/\t\t\tDocten Astrophys$/\t\tPhD\tAstrophysique/;
  s/\t\t\tDoct en Sc & Tech Environ$/\t\tPhD\tSciences et techniques environnementales/;
  s/\t\t\tDoctScde la Vie$/\t\tPhD\tBiologie/;
  s/\t\t\tDoctInformatique Fondamentale$/\t\tPhD\tInformatique Fondamentale/;
  s/\t\t\tDoctorat Scde la Vie$/\t\tPhD\tBiologie/;
  s/\t\t\tDocten PhysPlasmas Spatiaux$/\t\tPhD\tPhysique des plasmas spatiaux/;
  s/\t\t\tDocten Mécanique$/\t\tPhD\tMécanique/;
  s/\t\t\tDocten Robotique$/\t\tPhD\tRobotique/;
  s/\t\t\tDoctAcoustique$/\t\tPhD\tAcoustique/;
  s/\t\t\tDoctElectronique$/\t\tPhD\tÉlectronique/;
  s/\t\t\tDoct Neurosciences$/\t\tPhD\tNeurosciences/;
  s/\t\t\tDoct en Informatique$/\t\tPhD\tInformatique/;
  s/\t\t\tDoctImmunologie$/\t\tPhD\tImmunologie/;
  s/\t\t\tDocteur en Biologie$/\t\tPhD\tBiologie/;
  s/\t\t\tDoctMétéorologie$/\t\tPhD\tMétéorologie/;
  s/\t\t\tDoctès ScMicrobio$/\t\tPhD\tMicrobiologie/;
  s/\t\t\tDoctès Sc Virologie Moléculaire$/\t\tPhD\tVirologie Moléculaire/;
  s/\t\t\tDocten Biologie moléculaire$/\t\tPhD\tBiologie moléculaire/;
  s/\t\t\tDoct Mécanique\/Sc Matériaux$/\t\tPhD\tMécanique Sciences des matériaux/;
  s/\t\t\tDocten Virologie$/\t\tPhD\tVirologie/;
  s/\t\t\tDoct Environnement Marin$/\t\tPhD\tEnvironnement Marin/;
  s/\t\t\tDocten PhysMathématiques$/\t\tPhD\tPhysique Mathématiques/;
  s/\t\t\tDoct Biologie$/\t\tPhD\tBiologie/;
  s/\t\t\tDocteur en Biochimie$/\t\tPhD\tBiochimie/;
  s/\t\t\tDoct Phys des Solides$/\t\tPhD\tPhysique des solides/;
  s/\t\t\tDoctorat en Biologie$/\t\tPhD\tBiologie/;
  s/\t\t\tDoct en Sc Cognitives$/\t\tPhD\tSciences cognitives/;
  s/\t\t\tDoctorat Physique Solides$/\t\tPhD\tPhysique des solides/;
  s/\t\t\tDoctorat en Sc biomédicales$/\t\tPhD\tSciences biomédicales/;
  s/\t\t\tDoctès Sc Immunologie$/\t\tPhD\tImmunologie/;
  s/\t\t\tDoctorat Sc Cognitives$/\t\tPhD\tSciences cognitives/;
  s/\t\t\tDoctorat Bases fondamentales de l'Oncogénèse$/\t\tPhD\tBases fondamentales de l'Oncogénèse/;
  s/\t\t\tDoct en Océanologie$/\t\tPhD\tOcéanologie/;
  s/\t\t\tDocten Sc & Génie des Matériaux$/\t\tPhD\tGénie des Matériaux/;
  s/\t\t\tDoct en Sc de la Vie$/\t\tPhD\tBiologie/;
  s/\t\t\tDocten Physique du solide$/\t\tPhD\tPhysique du solide/;
  s/\t\t\tDoct en Automatique$/\t\tPhD\tAutomatique/;
  s/\t\t\tDocten Math appli Sci de l'homme$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDocten Sc forestières$/\t\tPhD\tSciences forestières/;
  s/\t\t\tDoctMathAutomatique$/\t\tPhD\tMathématique Automatique/;
  s/\t\t\tDocten Sc Cognitives$/\t\tPhD\tSciences cognitives/;
  s/\t\t\tDoctès Sc Histor et Philolog$/\t\tPhD\tHistoire/;
  s/\t\t\tDocten Physique des Solides$/\t\tPhD\tPhysique des solides/;
  s/\t\t\tThèse de doctorat oncogénèse$/\t\tPhD\tOncogénèse/;
  s/\t\t\tDocten Math Pures$/\t\tPhD\tMathématique pures/;
  s/\t\t\tDocten Sc de la Vie$/\t\tPhD\tBiologie/;
  s/\t\t\tDoctd'Etat en MathAppliquées$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDocten Physique Quantique$/\t\tPhD\tPhysique Quantique/;
  s/\t\t\tDocten Econ & Finance$/\t\tPhD\tÉcologie Finance/;
  s/\t\t\tDoctès Sc Bactériologie$/\t\tPhD\tBactériologie/;
  s/\t\t\tDoctorat Neurosciences$/\t\tPhD\tNeurosciences/;
  s/\t\t\tDoctorat de Biologie Moléculaire de la Cellule$/\t\tPhD\tBiologie Moléculaire de la Cellule/;
  s/\t\t\tDoctorat Biochimie$/\t\tPhD\tBiochimie/;
  s/\t\t\tDocten Physique des Lasers$/\t\tPhD\tPhysique des Lasers/;
  s/\t\t\tThèse Docten Informatique et Réseau$/\t\tPhD\tInformatique et Réseau/;
  s/\t\t\tDocten Histoire$/\t\tPhD\tHistoire/;
  s/\t\t\tDoct Physique des Particules CNRS-CERN$/\t\tPhD\tPhysique des Particules/;
  s/\t\t\tDoctd'Etat en Physique expérimentale$/\t\tPhD\tPhysique expérimentale/;
  s/\t\t\tDoctd'Etat en Sciences théoriques$/\t\tPhD\tSciences théoriques/;
  s/\t\t\tDoct en Math appliqués$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tIngDoct en Sciences$/\t\tPhD\tSciences/;
  s/\t\t\tDoct en Math Appliquées$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDoctd'Etat en Mathématiques$/\t\tPhD\tMathématiques/;
  s/\t\t\tDoct Biologie moléculaire et céllulaire végétale$/\t\tPhD\tBiologie moléculaire et céllulaire végétale/;
  s/\t\t\tDoct de Neurosciences$/\t\tPhD\tNeurosciences/;
  s/\t\t\tPhDMaths$/\t\tPhD\tMathématiques/;
  s/\t\t\tPhDBiophysique$/\t\tPhD\tBiophysique/;
  s/\t\t\tPhD Immunology$/\t\tPhD\tImmunologie/;
  s/\t\t\tPhD Physique$/\t\tPhD\tPhysique/;
  s/\t\t\tPhD Océanographie$/\t\tPhD\tOcéanographie/;
  s/\t\t\tPhD Math Appliqués$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tPhD Génie Chimique$/\t\tPhD\tGénie chimique/;
  s/\t\t\tPhD of Mathematics$/\t\tPhD\tMathématiques/;
  s/\t\t\tPhD of Computer Sciences$/\t\tPhD\tInformatique/;
  s/\t\t\tPhD Chimie$/\t\tPhD\tChimie/;
  s/\t\t\tPhD Electrical Engineering$/\t\tPhD\tIngénierie électrique/;
  s/\t\t\tPhD Information theory$/\t\tPhD\tThéorie de l'information/;
  s/\t\t\tPhD Electrical Engin & Computer Science$/\t\tPhD\tIngénierie électrique Informatique/;
  s/\t\t\tThèse d'Astrophysique$/\t\tPhD\tAstrophysique/;
  s/\t\t\tThèse Maths$/\t\tPhD\tMathématiques/;
  s/\t\t\tThèse Océano Physique$/\t\tPhD\tOcéanographie Physique/;
  s/\t\t\tThèse de Statist$/\t\tPhD\tStatistiques/;
  s/\t\t\tThèse de Physique$/\t\tPhD\tPhysique/;
  s/\t\t\tThèse Dépollution des Sols$/\t\tPhD\tDépollution des Sols/;
  s/\t\t\tThèse Mécanique$/\t\tPhD\tMécanique/;
  s/\t\t\tThèse de Neurobiologie$/\t\tPhD\tNeurobiologie/;
  s/\t\t\tThèse en Math$/\t\tPhD\tMathématiques/;
  s/\t\t\tThèse Génétique$/\t\tPhD\tGénétique/;
  s/\t\t\tThèse Physique$/\t\tPhD\tPhysique/;
  s/\t\t\tThèse en cryptographie$/\t\tPhD\tCryptographie/;
  s/\t\t\tThèse de Biophysique Théorique$/\t\tPhD\tBiophysique Théorique/;
  s/\t\t\tThèse 3ème cycle Informatique$/\t\tPhD\tInformatique/;
  s/\t\t\tThèse Biologie marine$/\t\tPhD\tBiologie marine/;
  s/\t\t\tThèse en Scde l'Eau 1994$/\t\tPhD\tScience de l'eau/;
  s/\t\t\tThèse en Hydrogéologie$/\t\tPhD\tHydrogéologie/;
  s/\t\t\tThèse Chimie appliquée$/\t\tPhD\tChimie appliquée/;
  s/\t\t\tThèse Phys Théor$/\t\tPhD\tPhysique Théorique/;
  s/\t\t\tThèse Physique Théorique$/\t\tPhD\tPhysique Théorique/;
  s/\t\t\tThèse méthodes physiques en télédétection$/\t\tPhD\tMéthodes physiques en télédétection/;
  s/\t\t\tThèse en Géographie$/\t\tPhD\tGéographie/;
  s/\t\t\tThèse Math appliquées$/\t\tPhD\tMathématiques appliquées/;
  s/\t\t\tDoct INRIA$/\t\tPhD\t/;
  s/\t\t\tPhD INRIA$/\t\tPhD\t/;
  s/\t\t\tThèse de Doctorat$/\t\tPhD\t/;
  s/\t\t\tDoctorat$/\t\tPhD\t/;
  s/\t\t\tDoctorat Habil$/\t\tPhD\t/;
  s/\t\t\tDoctd'Etat$/\t\tPhD\t/;
  s/\t\t\tDoct3È Cycle$/\t\tPhD\t/;
  s/\t\t\tIngDoct$/\t\tPhD\t/;
  s/\t\t\tDoctIng$/\t\tPhD\t/;
  s/\t\t\tDoctHabil$/\t\tPhD\t/;
  s/\t\t\tDoctUniversité$/\t\tPhD\t/;
  s/\t\t\tPhD$/\t\tPhD\t/;
  s/\t\t\tPhD Univ$/\t\tPhD\t/;
  s/\t\t\tPhD université$/\t\tPhD\t/;
  s/\t\t\tPhD Univ$/\t\tPhD\t/;
  s/\t\t\tPhD CEA$/\t\tPhD\t/;
  s/\t\t\tThèse d\'Etat$/\t\tPhD\t/;
  s/\t\t\tThèse$/\t\tPhD\t/;
  s/\t\t\tCertifié Langues Orientales$/\t\tCAPES\tLangues Orientales/;
  s/\t\t\tCAPES de lettres classiques$/\t\tCAPES\tLettres classiques/;
  s/\t\t\tAgrégé d'Univers$/\t\tAgr.\t/;
  s/\t\t\tAgrégé de (.*)$/\t\tAgr.\t\1/;
  s/\t\t\tAgrégée de (.*)$/\t\tAgr.\t\1/;
  s/\t\t\tAgrégé ScEcon$/\t\tAgr.\tÉconomie/;
  s/\t\t\tAgrégé en Sciences Physiques$/\t\tAgr.\tPhysique/;
  s/\t\t\tHabilitation en Physique$/\t\tHDR\tPhysique/;
  s/\t\t\tHDR en (.*)$/\t\tHDR\t\1/;
  s/\t\t\tHDR Physique$/\t\tHDR\tPhysique/;
  s/\t\t\tHDR Sciences de la Vie$/\t\tHDR\tBiologie/;
  s/\t\t\tHDR ScEco$/\t\tHDR\tÉconomie/;
  s/\t\t\tHDR$/\t\tHDR\t/;
  s/\t\t\tHabilitation U$/\t\tHDR\t/;
  s/\t\t\tHabilitation à Diriger des Recherche$/\t\tHDR\t/;
  s/\t\t\tHabilitation à diriger des Recherches$/\t\tHDR\t/;
  s/\t\t\tHabilitation à diriger les recherches$/\t\tHDR\t/;
  s/\t\t\tHabilitation à diriger des recherches$/\t\tHDR\t/;
  s/\t\t\tHabil DirRecherche$/\t\tHDR\t/;
  s/\t\t\tHabilitation à diriger des Rech$/\t\tHDR\t/;
  s/\t\t\tM Sc Nucl Eng$/\t\tMSc\tNucléaire/;
  s/\t\t\tDES ScEconom$/\t\tDESS\tÉconomie/;
  s/\t\t\tMS RechOpér$/\t\tMSc\tRecherche Opérationnelle/;
  s/\t\t\tDES Economie$/\t\tDESS\tÉconomie/;
  s/\t\t\tMSEE Fla USA$/\t\tMSc\tElectrical Engineering Fla USA/;
  s/\t\t\tMSEE$/\t\tMSc\tElectrical Engineering/;
  s/\t\t\tMS Business$/\t\tMSc\tBusiness/;
  s/\t\t\tDr Physchimbiotransformation$/\t\tPhD\tPhyschimbiotransformation/;
  s/\t\t\tMaster Hydraulique$/\t\tM\tHydraulique/;
  s/\t\t\tMS Mechanical Engineering$/\t\tMSc\tMechanical Engineering/;
  s/\t\t\tSM Management$/\t\tMSc\tManagement/;
  s/\t\t\tMScDIC$/\t\tMSc\t/;
  s/\t\t\tMIB$/\t\tMIB\t/;
  s/\t\t\tDECF$/\t\tDESCF\t/;
  s/\t\t\tMaster Aérospace$/\t\tM\tAérospace/;
  s/\t\t\tMS AéroAstro &EECS$/\t\tMSc\tAéronautique Astrophysique/;
  s/\t\t\tMS Economie$/\t\tMSc\tÉconomie/;
  s/\t\t\tMaster EnginScience$/\t\tM\tEngineering science/;
  s/\t\t\tMS in Finance$/\t\tMSc\tFinance/;
  s/\t\t\tMS Transportation$/\t\tMSc\tTransportation/;
  s/\t\t\tMaster en Pétrole Engineering$/\t\tM\tPétrole Engineering/;
  s/\t\t\tMSc Public Policy$/\t\tMSc\tPublic Policy/;
  s/\t\t\tDES Droit Public$/\t\tDESS\tDroit public/;
  s/\t\t\tMA Industrial Design Eng$/\t\tMA\tIndustrial Design Engineering/;
  s/\t\t\tMaster of Space System Engineering$/\t\tM\tSpace System Engineering/;
  s/\t\t\tMS Chemical Engineering$/\t\tMSc\tChimie/;
  s/\t\t\tMPhil$/\t\tMPhil\t/;
  s/\t\t\tMS Ing & Gestion Energie$/\t\tMSc\tIngénierie et gestion énergétique/;
  s/\t\t\tDES$/\t\tDESS\t/;
  s/\t\t\tMBA Univ$/\t\tMBA\t/;
  s/\t\t\tDES ScPhys$/\t\tDESS\tPhysique/;
  s/\t\t\tDr Trait Signal$/\t\tPhD\tTraitement du signal/;
  s/\t\t\tMS Probalilité & Finance$/\t\tMSc\tProbalilité et Finance/;
  s/\t\t\tDULCO Chinois$/\t\tDEUG\tDULCO de chinois/;
  s/\t\t\tDRES Sciences$/\t\tDESS\tSciences/;
  s/\t\t\tMSc Electrical Engineering$/\t\tMSc\tElectrical Engineering/;
  s/\t\t\tDU Médiateur Judiciaire et conventionnelle$/\t\tDEUG\tMédiateur Judiciaire et conventionnelle/;
  s/\t\t\tMaster AMUR$/\t\tM\tAMUR/;
  s/\t\t\tMSc en Mécanique$/\t\tMSc\tMécanique/;
  s/\t\t\tMS Management Aéroportuaire$/\t\tMSc\tManagement Aéroportuaire/;
  s/\t\t\tMS spécialisé en sécurité des syst d'inform$/\t\tMSc\tSécurité des système d'information/;
  s/\t\t\tMScin applied Mathematics$/\t\tMSc\tMathématiques appliquées/;
  s/\t\t\tEMBA 2005$/\t\tMBA\t/;
  s/\t\t\tMaster Droit des affaires Int & Eur$/\t\tM\tDroit des affaires Intérieures et Européennes/;
  s/\t\t\tMaster de Management par les compétences et organisations$/\t\tM\tManagement par les compétences et organisations/;
  s/\t\t\tEtudes sup Comptables & Financières$/\t\tDESCF\t/;
  s/\t\t\tMaster d'Histoire$/\t\tM\tHistoire/;
  s/\t\t\tMaster en Electronique$/\t\tM\tÉlectronique/;
  s/\t\t\tEngineering Management Certificate$/\t\tLic.\tEngineering Management/;
  s/\t\t\tMS Finance de Marché$/\t\tMSc\tFinance de Marché/;
  s/\t\t\tMaster Adm des Entreprises$/\t\tM\tAdministration des Entreprises/;
  s/\t\t\tDES Sc économiques$/\t\tDESS\tÉconomie/;
  s/\t\t\tMaster Professionnel en Droit Fiscal$/\t\tM\tDroit Fiscal/;
  s/\t\t\tDES de Neurologie$/\t\tDESS\tNeurologie/;
  s/\t\t\tMs Affaires Internationales$/\t\tMSc\tAffaires Internationales/;
  s/\t\t\tMaster de Recherche Santé Publique$/\t\tM\tSanté Publique/;

  # Both diploma and university missing
  s/\t\t\tDipl Expert Compt$/\t\t\tExpertise comptable/;
  s/\t\t\tDipl Langues Orient Chinois$/\t\t\tLangues orientales (Chinois)/;
  s/\t\t\tDiplome d'Etat d'Educateur spécialisé$/\t\t\tÉducateur spécialisé/;
  s/\t\t\tDiplome Universitaire de Gestion$/\t\t\tGestion/;
  s/\t\t\tInstForm SupBiomédicale$/\t\t\tBiomédical/;

  # Double diploma that need to be splitted.
  s/^(FO\t\w{8}\t\t)\tDoct HDR Ecotoxicologie$/\1PhD\tÉcotoxicologie\n\1HDR\tÉcotoxicologie/;
  s/^(FO\t\w{8}\t\t)\tAgrégé et Doct en Génie civil$/\1PhD\tGénie civil\n\1Agr.\tGénie civil/;
  s/^(FO\t\w{8}\t\t)\tDoct Habilité à la dir de rech en Philosophie$/\1PhD\tPhilosophie\n\1HDR\tPhilosophie/;
  s/^(FO\t\w{8}\t\t)\tDEA\+ Thèse Doctorat Pharmacochimie moléculaire$/\1PhD\tPharmacochimie moléculaire\n\1DEA\tPharmacochimie moléculaire/;
  s/^(FO\t\w{8}\t\t)\tDoctorat\, HDR Informatique$/\1PhD\tInformatique\n\1HDR\tInformatique/;
  s/^(FO\t\w{8}\t\t)\tDoctorat et Habilitation$/\1PhD\t\n\1HDR\t/;
  s/^(FO\t\w{8}\t)\t\tPhD et Habil à diriger les RechUniv Paris 6$/\1UPMC\tPhD\t\n\1UPMC\tHDR\t/;
  s/^(FO\t\w{8}\t)\t\tMS & PhD EHESS$/\1EHESS\tPhD\t\n\1EHESS\tMSc\t/;
  s/^(FO\t\w{8}\t)\t\tMBAIEP Paris Lic de Droit Assas$/\1Sciences Po\tDipl.\t\n\1Assas\tLic.\tDroit/;
  s/^(FO\t\w{8}\t)\t\tIEP Paris Lic de Droit Assas$/\1Sciences Po\tDipl.\t\n\1Assas\tLic.\tDroit/;
  s/^(FO\t\w{8}\t)\t\tIngENST licencié sciences économiques$/\1Télécom\tIng.\t\n\1\tLic.\tÉconomie/;
  s/^(FO\t\w{8}\t\t)\tMastère Aménagement et Maitrise d'Ouvrage Urbaine$/\1M\tAménagement\n\1Maîtr.\tOuvrage Urbain/;
  s/^(FO\t\w{8}\t\t)\tDEA et Thèse de Biologie$/\1PhD\tBiologie\n\1DEA\tBiologie/;
  s/^(FO\t\w{8}\t)\t\tDEA Thèse Jussieu$/\1UPMC\tPhD\t\n\1UPMC\tDEA\t/;
  s/^(FO\t\w{8}\t\t)\tDESS CAAE MBA$/\1DESS\t\n\1MBA\t/;
  s/^(FO\t\w{8}\t)\t\tIngSupelec 86 - EMBA HEC 04$/\1Supélec\tIng.\t\n\1HEC\tMBA\t/;
  s/^(FO\t\w{8}\t)\t\tMBA MscMassachus$/\1MIT\tMBA\t\n\1MIT\tMSc\t/;
  s/^(FO\t\w{8}\t)\t\tMBA Columbia \+ LBS/\1Columbia University\tMBA\t\n\1London Business School\tM\t/;
  s/^(FO\t\w{8}\t)\t\tMS Columbia & sciences Po/\1Columbia University\tMSc\t\n\1Sciences Po\tDipl.\t/;

  #############################################################################
  # Devel formatting.
  # # Both university and diploma missing.
  #s/^FO\t\w{8}\t\t\tExpertise comptable$//;
  #s/^FO\t\w{8}\t\t\tLangues orientales \(Chinois\)$//;
  #s/^FO\t\w{8}\t\t\tÉducateur spécialisé$//;
  #s/^FO\t\w{8}\t\t\tGestion$//;
  #s/^FO\t\w{8}\t\t\tBiomédical$//;
  #s/^FO\t\w{8}\t\t\tBrth$//;
  #s/^FO\t\w{8}\t\t\tDEM$//;
  #s/^FO\t\w{8}\t\t\tDT$//;
  #s/^FO\t\w{8}\t\t\tBESG$//;
  #s/^FO\t\w{8}\t\t\tESO$//;
  #s/^FO\t\w{8}\t\t\tBT$//;
  #s/^FO\t\w{8}\t\t\tBEL$//;
  #s/^FO\t\w{8}\t\t\tDipl Lt Et Sup Banq$//;
  #s/^FO\t\w{8}\t\t\tDiplôme Nepali-Tibétain$//;
  #s/^FO\t\w{8}\t\t\tReact School Harwell$//;
  #s/^FO\t\w{8}\t\t\tEATG$//;
  #s/^FO\t\w{8}\t\t\tDESA$//;
  #s/^FO\t\w{8}\t\t\tDIUUP$//;
  #s/^FO\t\w{8}\t\t\tDrrerNat$//;
  #s/^FO\t\w{8}\t\t\tIAC$//;
  #s/^FO\t\w{8}\t\t\tCESDR$//;
  #s/^FO\t\w{8}\t\t\tAuditeur ScPolitique$//;
  #s/^FO\t\w{8}\t\t\tCES Informatique$//;
  #s/^FO\t\w{8}\t\t\tDon en religion$//;
  #s/^FO\t\w{8}\t\t\tDSN$//;
  #s/^FO\t\w{8}\t\t\tBEMS\/CHEM$//;
  #s/^FO\t\w{8}\t\t\tCESSID$//;
  #s/^FO\t\w{8}\t\t\tBiologie Moléculaire$//;
  #s/^FO\t\w{8}\t\t\tMécanique des Transfert$//;
  #s/^FO\t\w{8}\t\t\tGestion$//;
  #s/^FO\t\w{8}\t\t\tDECS$//;
  #s/^FO\t\w{8}\t\t\tCFAF$//;
  #s/^FO\t\w{8}\t\t\tCRC$//;
  #s/^FO\t\w{8}\t\t\tMASE$//;
  #s/^FO\t\w{8}\t\t\tCollège des Sciences Soc et Eco$//;
  #s/^FO\t\w{8}\t\t\tInstitut de Contrôle de Gestion$//;
  #s/^FO\t\w{8}\t\t\tICG$//;
  #s/^FO\t\w{8}\t\t\tETS II$//;
  #s/^FO\t\w{8}\t\t\tFRM$//;
  #s/^FO\t\w{8}\t\t\tArchitecte DPLG$//;
  #s/^FO\t\w{8}\t\t\tCycle des Hautes Etudes CHEE$//;
  #s/^FO\t\w{8}\t\t\tCHEE&DD Session 9$//;
  #s/^FO\t\w{8}\t\t\tCSME Session 29$//;
  #s/^FO\t\w{8}\t\t\tInternat Teachers Progr$//;
  #s/^FO\t\w{8}\t\t\tCSCP$//;
  #s/^FO\t\w{8}\t\t\tBaccalauréat canonique$//;
  #s/^FO\t\w{8}\t\t\tCertif européen de Psychothérapie$//;
  #s/^FO\t\w{8}\t\t\tIFG$//;
  #s/^FO\t\w{8}\t\t\tIFP$//;
  #s/^FO\t\w{8}\t\t\tArchitecte dplg$//;
  #s/^FO\t\w{8}\t\t\tLLCE Chinois INALCO$//;
  #s/^FO\t\w{8}\t\t\tInst du Contrôle de Gestion$//;
  #s/^FO\t\w{8}\t\t\tInstitut Auguste Comte$//;
  #s/^FO\t\w{8}\t\t\tInst Auguste Comte$//;
  #s/^FO\t\w{8}\t\t\tUSMC Command & Staff College$//;
  #s/^FO\t\w{8}\t\t\tISNSE Argunne National Laboratory USA$//;
  ## # Formatted stuff.
  #s/^FO\t\w{8}((\t|\t\t)[a-zA-Z1-9'\.éèêùüàäïîşńÉÈÊÙÀÜÄÏÎŞŃ \-\(\)]+)\t.*//;
  # # Removes empty lines.
  s/^\n//;

  print OUT $_;
}

close(FILE);
close(OUT);
